"""Contract: prose ``N primitives`` references stay near the real count.

Several markdown files quote a primitive count in prose — ``README.md``
says ``~50 primitives``. The real count is 55+ and growing. Each new
primitive widens the gap silently until someone notices the docs lie.

The test walks a set of doc files, regex-finds ``N primitives``, and
asserts the integer is within ±2 of ``len(get_registry())`` OR contains
``auto-generated`` nearby (auto-regenerated catalogs like
``docs/generated/operations.md`` are allowed to carry exact numbers).

Scope note (plan A6, 2026-07-15). The ``docs/internals`` +
``docs/workflows`` surfaces moved to the STRICT-equality pin
:mod:`tests.contracts.test_doc_frozen_counts`, which covers the whole count
family (primitives / verbs / schemas / error codes / regen scripts) to
exact equality — strictly dominating this ±2 primitives-only check there.
So those files were dropped from :data:`_SCANNED_FILES` below; this pin now
guards only the out-of-A6-scope surfaces (``README.md`` and
``docs/reference/``), where the ±2 tolerance and primitives-only focus are
still the right call. (Dropping ``adding-a-primitive.md`` here also defused
a latent time bomb: its "167 primitives" sat at ``|167-169| == 2``, exactly
this pin's tolerance, so the next primitive addition would have turned this
test red on a doc it no longer needs to watch.)

False positives — prose like ``the first 50 primitives we added were…``
where the number is a historical reference, not a count — go in
:data:`_ALLOWLIST` with a comment so contributors notice on each new
addition.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from hpc_agent._kernel.registry.primitive import PrimitiveMeta
from tests._registry_helpers import core_only_registry

_REPO_ROOT = Path(__file__).resolve().parents[2]

# Files to scan. Each path is relative to the repo root. The
# ``docs/internals`` + ``docs/workflows`` surfaces are intentionally ABSENT:
# they moved to the strict-equality pin (test_doc_frozen_counts, plan A6),
# which dominates this ±2 check there. What remains is A6's out-of-scope
# surfaces — ``README.md`` and ``docs/reference/`` — plus the two other
# non-internals READMEs this pin has always watched.
_SCANNED_FILES: tuple[str, ...] = (
    "README.md",
    "docs/README.md",
    "docs/integrations/CONTRACT.md",
    "docs/reference/agent-surface.md",
    "docs/reference/boundary-contract.md",
    "docs/reference/cli-spec.md",
    "docs/reference/config-precedence.md",
    "docs/reference/env-vars.md",
    "docs/reference/python-api-contract.md",
    "docs/reference/reducer-contract.md",
    "docs/reference/scheduler-states.md",
)

# Pair of (file-relpath, exact substring) for prose where the number
# is intentionally a historical reference. Default policy is fail-loud;
# this allowlist is for the rare case where the prose really does
# mean a fixed historical count.
_ALLOWLIST: set[tuple[str, str]] = set()

# Tolerance on the count comparison. Set generously so a doc that
# missed the most recent primitive addition by one or two doesn't
# fail CI on the very same PR — the goal is to catch the silent
# drift (50 → 70), not to require lockstep updates.
_TOLERANCE: int = 2

# Marker substrings near a numeric primitive count that exempt it from
# the ±tolerance check (the file is auto-generated and may carry an
# exact number).
_EXEMPT_MARKERS: tuple[str, ...] = ("auto-generated", "auto-regenerated", "generated by")

# Regex matching ``N primitives`` (with optional ``~`` prefix). The
# digit group is what we compare against the registry.
_PROSE_RE = re.compile(r"~?\b(\d+)\s+primitives?\b")


@pytest.fixture(scope="module")
def registry() -> dict[str, PrimitiveMeta]:
    # Filter to core-only: the prose docs scanned below describe core's
    # primitive surface. When a plugin is also installed, its primitives
    # show up in the live registry but the prose counts don't track them.
    return core_only_registry()


def _file_is_auto_generated(text: str) -> bool:
    """True iff the file declares itself auto-generated at the top."""
    head = text[:400].lower()
    return any(marker in head for marker in _EXEMPT_MARKERS)


def _match_is_auto_generated(text: str, match: re.Match[str]) -> bool:
    """True iff *match* sits within a few lines of an auto-generated marker."""
    start = max(0, match.start() - 200)
    end = min(len(text), match.end() + 200)
    window = text[start:end].lower()
    return any(marker in window for marker in _EXEMPT_MARKERS)


def test_prose_primitive_counts_track_registry(
    registry: dict[str, PrimitiveMeta],
) -> None:
    """Every ``N primitives`` mention must be within ±2 of the real count."""
    real_count = len(registry)
    offenders: list[str] = []
    for rel in _SCANNED_FILES:
        path = _REPO_ROOT / rel
        if not path.is_file():
            # Missing optional doc files are fine; the test is not the
            # right place to require their existence.
            continue
        text = path.read_text(encoding="utf-8")
        if _file_is_auto_generated(text):
            continue
        for match in _PROSE_RE.finditer(text):
            substring = match.group(0)
            if (rel, substring) in _ALLOWLIST:
                continue
            if _match_is_auto_generated(text, match):
                continue
            claimed = int(match.group(1))
            if abs(claimed - real_count) > _TOLERANCE:
                offenders.append(
                    f"  {rel}: prose says {substring!r}, registry has {real_count} "
                    f"(diff={claimed - real_count}; tolerance=±{_TOLERANCE})"
                )

    assert not offenders, (
        "Prose primitive counts have drifted from the registry. Update "
        "the docs OR add the (file, substring) pair to _ALLOWLIST if "
        "the number is a deliberate historical reference:\n" + "\n".join(offenders)
    )
