"""Minimal HPC executor scaffold — pure compute, no CLI surface.

This template lands in the experiment repo (e.g. ``src/<name>.py``)
and demonstrates the only contract every executor must satisfy:

    Expose ``compute(args) -> None``.

That's it. CLI dispatch lives in ``.hpc/cli.py`` (auto-generated by
``/submit-hpc`` in the experiment repo); the per-executor flag list
is declared in ``.hpc/tasks.py`` FLAGS, keyed by importable module
path. The dispatcher parses argv against the right FLAGS, then calls
``compute(args)`` here.

Cluster invocation:

    python -m cli src.<this_module> --output-file ... <other flags>

There is no ``if __name__ == "__main__":`` block here. The dispatcher
is the entry point — running this file directly with ``python`` won't
do anything useful.

Convention details:

* ``args.output_file`` is the only flag the framework guarantees
  (provided by ``generic_args()`` in every FLAGS list). All other
  flags come from the experiment's per-executor entry in
  ``.hpc/tasks.py`` FLAGS — e.g. ``flag("horizon", int, default=1)``
  becomes ``args.horizon``.
* Writes the per-task result to ``args.output_file`` (CSV / Parquet /
  JSON — format is the executor's call).
* Optionally calls
  :func:`hpc_agent.models.mapreduce.metrics_io.write_metrics` with a dict of
  scalar summaries when ``$RESULT_DIR`` is set, so the on-cluster
  combiner can aggregate per grid point. No-op outside the HPC
  dispatcher.

Reproducibility (parity with a serial run):

* **Seed deterministically from ``HPC_TASK_ID``** (or a kwarg derived
  from it in ``tasks.py``). Same task_id → same numbers regardless of
  which compute node it lands on. The dispatcher exports
  ``HPC_TASK_ID`` for every task; reading it here is the difference
  between "deterministic across the array" and "wall-clock-seeded
  every run."
* **Read kwargs from ``HPC_KW_<KEY>`` rather than the bare uppercase
  ``<KEY>``.** The dispatcher exports both forms by default for back-
  compat, but the bare form silently overwrites real env vars (a
  kwarg named ``home`` becomes ``$HOME``). The ``HPC_KW_*`` namespace
  is collision-free.
* **Pin thread counts before importing numpy/scipy/torch** if you do
  numerical reductions. The cluster preamble already defaults
  ``OMP_NUM_THREADS=1`` etc., but doing it inside the executor too
  makes the executor reproducible when run serially outside the
  framework.

Smoke test during development (mimics the dispatcher env)::

    HPC_TASK_ID=0 RESULT_DIR=/tmp/out python -c \
        "import argparse; \
         from src.<this_module> import compute; \
         compute(argparse.Namespace(output_file='/tmp/out.csv'))"
"""

# ruff: noqa: E501  (LLM-facing scaffolds read better with long lines)

from __future__ import annotations

import csv
import os
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import argparse


def compute(args: argparse.Namespace) -> None:
    """Run the experiment for one task and write its result file.

    TODO: replace with the experiment's real computation. The ``args``
    Namespace is whatever the dispatcher parsed from argv against this
    executor's per-key entry in ``.hpc/tasks.py`` FLAGS.
    """
    # Reproducibility seed. Falls back to ``args.seed`` (the
    # generic_args default of 42) when run serially outside the
    # dispatcher. ``HPC_TASK_ID`` makes parallel tasks differ
    # deterministically; ``args.seed`` keeps a serial smoke-test
    # bit-identical across runs.
    _seed = int(os.environ.get("HPC_TASK_ID", str(getattr(args, "seed", 42))))
    # Pass _seed to your RNG, e.g.:
    #     rng = numpy.random.default_rng(_seed)
    # ``np.random.default_rng`` is preferred over ``np.random.seed`` —
    # the latter mutates a process-global state and is not thread-safe.

    # Example minimal output: one-row CSV with a placeholder metric.
    result: dict[str, Any] = {"value": 0.0, "n_samples": 0, "seed": _seed}

    os.makedirs(os.path.dirname(args.output_file) or ".", exist_ok=True)
    with open(args.output_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(list(result.keys()))
        writer.writerow(list(result.values()))

    # Optional: emit metrics.json sidecar for the cluster combiner.
    # No-op outside the HPC dispatcher (when $RESULT_DIR is unset) so
    # the scaffold stays standalone-runnable for local smoke tests.
    if os.environ.get("RESULT_DIR"):
        from hpc_agent.models.mapreduce.metrics_io import write_metrics

        write_metrics(result)


# ── Common patterns (reference, not active code) ─────────────────────────
#
# The snippets below illustrate three typical compute() shapes. Copy and
# adapt the one that matches your experiment. None of them are baked
# into the framework — flags are declared in .hpc/tasks.py FLAGS.
#
# 1. ML training / forecasting (FLAGS: horizon, train_window, alpha, ...)
#
#    def compute(args):
#        df = load_data(args.data_path)
#        train, test = walk_forward_split(df, args.start, args.end, args.horizon)
#        model = fit(train, alpha=args.alpha)
#        preds = model.predict(test)
#        metrics = {"qlike": qlike(test.y, preds), "n_samples": len(test)}
#        write_csv(args.output_file, preds)
#        if os.environ.get("RESULT_DIR"):
#            from hpc_agent.models.mapreduce.metrics_io import write_metrics
#            write_metrics(metrics)
#
# 2. Simulation / seed-sweep (FLAGS: seed, steps, config, ...)
#
#    def compute(args):
#        rng = numpy.random.default_rng(args.seed)
#        traj = run_simulation(config=args.config, steps=args.steps, rng=rng)
#        scalars = summarize(traj)
#        write_json(args.output_file, scalars)
#
# 3. Sharded data-processing (FLAGS: shard_id, n_shards, input_glob, ...)
#
#    def compute(args):
#        files = sorted(glob.glob(args.input_glob))
#        my_files = files[args.shard_id::args.n_shards]
#        rows = sum((process(f) for f in my_files), [])
#        write_parquet(args.output_file, rows)
#
# ── PyTorch determinism (drop in if you import torch) ─────────────────────
#
#    import torch
#    torch.manual_seed(_seed)
#    torch.cuda.manual_seed_all(_seed)
#    torch.use_deterministic_algorithms(True)
#    torch.backends.cudnn.deterministic = True
#    torch.backends.cudnn.benchmark = False
#    # CUBLAS_WORKSPACE_CONFIG=:4096:8 is required for the above to work
#    # on CUDA matmuls; the framework's gpu_preamble.sh exports it.
#    # If you use DataLoader(num_workers>0), pass:
#    #     g = torch.Generator(); g.manual_seed(_seed)
#    #     DataLoader(..., generator=g,
#    #                worker_init_fn=lambda i: numpy.random.seed(_seed + i))
#
# ── Reading kwargs from HPC_KW_* (collision-free) ─────────────────────────
#
# The dispatcher exports each kwarg as both ``HPC_KW_<KEY>`` and bare
# ``<KEY>`` (uppercased). The bare form can shadow real env vars
# (``home`` → ``$HOME``); prefer the namespaced form when reading from
# os.environ rather than from args.<name>:
#
#    horizon = int(os.environ.get("HPC_KW_HORIZON", "1"))
#
# (When the .hpc/cli.py dispatcher hands you ``args``, this is a moot
# point — argparse parses from the CLI, not the env. The env-var form
# matters only if your shell command in the spec uses ``$HORIZON`` or
# you read kwargs from inside a non-Python wrapper.)
