"""Content-addressed cache for LLM-generated chunking shims.

The shim itself is generated by the LLM (it adapts to each executor's CLI and data
pipeline). This module makes the generated artifact reusable: the same
``(executor_source, template_source)`` pair always maps to the same cache key, so
re-running ``/submit`` against an unchanged executor yields a byte-identical shim.
"""

from __future__ import annotations

__all__ = [
    "SHIM_STAMP_PREFIX",
    "shim_cache_key",
    "stamp_shim",
    "load_cached_shim",
    "save_shim",
]

import hashlib
import json
import shutil
import time
from pathlib import Path

SHIM_STAMP_PREFIX = "# hpc-shim-key: "


def shim_cache_key(executor_path: Path, template_path: Path) -> str:
    """Content hash of ``(executor_source, template_source)``.

    Using content (not mtime) keeps the key stable across rsync, git checkout, and
    re-clones.
    """
    executor_bytes = Path(executor_path).read_bytes()
    template_bytes = Path(template_path).read_bytes()
    h = hashlib.sha256()
    h.update(executor_bytes)
    h.update(b"\n---\n")
    h.update(template_bytes)
    return h.hexdigest()


def stamp_shim(shim_source: str, key: str) -> str:
    """Prepend ``# hpc-shim-key: <key>`` to *shim_source* if not already stamped."""
    stamp = f"{SHIM_STAMP_PREFIX}{key}\n"
    if shim_source.startswith(stamp):
        return shim_source
    first_line = shim_source.split("\n", 1)[0]
    if first_line.startswith(SHIM_STAMP_PREFIX):
        _, _, rest = shim_source.partition("\n")
        return stamp + rest
    return stamp + shim_source


def _cache_paths(cache_dir: Path, key: str) -> tuple[Path, Path]:
    shim_dir = Path(cache_dir) / "shims"
    return shim_dir / f"{key}.py", shim_dir / f"{key}.meta.json"


def load_cached_shim(cache_dir: Path, key: str) -> Path | None:
    """Return the cached shim path if a hit exists for *key*, else ``None``."""
    shim_path, _ = _cache_paths(cache_dir, key)
    return shim_path if shim_path.is_file() else None


def save_shim(
    cache_dir: Path,
    key: str,
    shim_source: str,
    *,
    executor_path: Path | None = None,
    template_path: Path | None = None,
    materialize_at: Path | None = None,
) -> Path:
    """Persist *shim_source* under the cache key and optionally copy it to a working path.

    Returns the path of the cached shim. Writes a sidecar ``<key>.meta.json`` for
    debuggability. If *materialize_at* is supplied, the cached shim is copied there
    verbatim (so the downstream rsync-and-run flow keeps working).
    """
    shim_path, meta_path = _cache_paths(cache_dir, key)
    shim_path.parent.mkdir(parents=True, exist_ok=True)

    stamped = stamp_shim(shim_source, key)
    shim_path.write_text(stamped)

    meta = {
        "key": key,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    if executor_path is not None:
        meta["executor_path"] = str(executor_path)
    if template_path is not None:
        meta["template_path"] = str(template_path)
    meta_path.write_text(json.dumps(meta, indent=2, sort_keys=True))

    if materialize_at is not None:
        dest = Path(materialize_at)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(shim_path, dest)

    return shim_path
