"""``validate-scaffold-staleness`` primitive — pre-submit stale-scaffold gate (#364).

A ``.hpc/`` scaffold generated by an *older* hpc-agent can survive an
upgrade and then fail on the cluster with a runtime ``ImportError``,
because nothing at submit time checked that the generated scaffold's
``hpc_agent.*`` imports still resolve against the *installed* package.
The observed case was a pre-reorg ``.hpc/_build_tasks.py`` importing
``from hpc_agent.template import ...`` after ``hpc_agent.template`` was
consolidated away — the only signal the user got was a far-downstream
``ImportError`` on a compute node, not a cheap local refusal.

This validator is the local (no-SSH) submit-time check. It delegates to
:func:`hpc_agent.incorporation.build.scaffold_meta.check_scaffold_staleness`,
which is a **no-op when the scaffold's generator-version stamp matches the
installed version** (so a current-version scaffold submits with
byte-identical behaviour) and otherwise scans the generated files'
``hpc_agent`` imports against the installed package. A stale scaffold
produces a single ``error``-severity ``stale_scaffold`` finding whose
``suggested_fix`` points at regenerating the framework-owned scaffold (the
fix is regeneration via onboarding, NOT hand-editing the generated file).

Like every validator: it returns findings, never raises — the
``validate-campaign`` composer escalates any ``error`` finding to
``overall="fail"``, which aborts submit.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from hpc_agent._kernel.registry.primitive import primitive
from hpc_agent._wire.validators.validate_scaffold_staleness import (
    ValidateScaffoldStalenessResult,
)
from hpc_agent._wire.workflows.validate_campaign import ValidatorFinding
from hpc_agent.incorporation.build.scaffold_meta import check_scaffold_staleness

if TYPE_CHECKING:
    from pathlib import Path

_VALIDATOR = "validate-scaffold-staleness"


@primitive(
    name=_VALIDATOR,
    verb="validate",
    side_effects=[],
    idempotent=True,
    idempotency_key="experiment_dir",
    agent_facing=True,
)
def validate_scaffold_staleness(experiment_dir: Path) -> ValidateScaffoldStalenessResult:
    """Refuse a ``.hpc/`` scaffold whose imports no longer resolve (#364).

    Returns a :class:`ValidateScaffoldStalenessResult`. When the scaffold's
    stamp matches the installed version the check is a no-op (``fresh``, no
    findings, no import scan). Otherwise an unresolvable import or a
    pre-reorg ``_build_tasks.py`` artifact yields a single ``error``-severity
    ``stale_scaffold`` finding carrying the broken imports + the legacy
    artifacts as evidence.
    """
    result = check_scaffold_staleness(experiment_dir)
    findings: list[ValidatorFinding] = []
    if result.stale:
        reason = "; ".join(result.reasons) or "the generated scaffold is incompatible"
        version_clause = (
            f"generated by hpc-agent {result.stamp_version} but {result.installed_version} "
            "is installed"
            if result.stamp_version
            else f"unstamped (legacy) scaffold checked against installed {result.installed_version}"
        )
        findings.append(
            ValidatorFinding(
                validator=_VALIDATOR,
                severity="error",
                code="stale_scaffold",
                message=(
                    f"The .hpc/ scaffold is stale ({version_clause}): {reason}. "
                    "It would fail with an ImportError on the cluster."
                ),
                suggested_fix=(
                    "Regenerate the framework-owned scaffold against the installed "
                    "hpc-agent — re-run onboarding (hpc-wrap-entry-point / interview) "
                    "or `hpc-agent build-tasks-py --force`. Do NOT hand-edit the "
                    "generated file; it is superseded, not source."
                ),
                evidence={
                    "installed_version": result.installed_version,
                    "stamp_version": result.stamp_version,
                    "legacy_artifacts": result.legacy_artifacts,
                    "unresolved_imports": result.unresolved_imports,
                    "scanned_files": result.scanned_files,
                },
            )
        )
    return ValidateScaffoldStalenessResult(
        findings=findings,
        status=result.status,  # type: ignore[arg-type]  # "fresh"/"stale" both valid
        installed_version=result.installed_version,
        stamp_version=result.stamp_version,
    )
