"""``program-init`` — materialize (or adopt) a PROGRAM pack layer from a domain seam.

The seat that builds plan item P1a (``docs/design/program-init.md``): the three-tier
pack architecture's PROGRAM edge. A domain pack ships the reusable skeleton; at
program creation this verb CONSUMES that skeleton to generate a program template,
stamps the lineage (``derived_from {pack, seam, version, sha}``) MECHANICALLY,
seals the program manifest via the generic pack re-seal, and binds the packs — one
command = a working program layer. Lineage is code-authored, never asked (P3).

Two modes:

* **create** — generate ``packs/<program>/`` fresh: a VERBATIM byte copy of the
  domain ``audit_template`` seam file (DP1 — core never interprets template
  content) plus a code-authored provenance header, a ``sweep.json`` recipe carrying
  the lineage stamp, a sealed ``manifest.json``, and binds of both packs.
* **adopt** — migrate an EXISTING program pack onto its real lineage WITHOUT
  byte-changing any content file (the signed-template migration path, memo hazard
  2): stamp the recipe, reseal the manifest, rebind ONLY the pack whose bytes
  moved. The domain pack (a lineage root) is untouched — no no-op rebind.

The check leg runs a caller-resolvable command ONLY (``spec.check`` or, absent
that, reports the domain pack's receipt slots as to-earn). Core never composes an
argv from pack content (DP2/DP4) — ``program-init`` reuses the same subprocess seat
``pack-refresh`` does.

Lives inside the ``pack`` subject, reaching only ``state.*`` + the same-subject
``ops.pack.bind_op`` / ``ops.pack.refresh_op`` — the subject-imports lint is
satisfied by construction (the ``refresh_op`` posture).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import TYPE_CHECKING, Any

from hpc_agent import errors
from hpc_agent._kernel.registry.primitive import SideEffect, primitive
from hpc_agent._wire.actions.pack_bind import PackBindSpec
from hpc_agent._wire.actions.program_init import (
    DerivedFromEcho,
    PackOptInEcho,
    ProgramBind,
    ProgramInitResult,
    ProgramInitSpec,
    ProgramSlotToEarn,
    ReceiptBindingEcho,
)
from hpc_agent.cli._dispatch import CliShape, SchemaRef
from hpc_agent.infra.io import append_jsonl_line, atomic_write_text
from hpc_agent.infra.time import utcnow
from hpc_agent.ops.pack.bind_op import pack_bind
from hpc_agent.ops.pack.refresh_op import (
    check_timeout_sec,
    pack_checks_log_path,
    read_packs_optin,
    run_check_command,
    slot_check_commands,
)
from hpc_agent.state import pack, pack_sweep
from hpc_agent.state.decision_journal import read_decisions
from hpc_agent.state.pack_receipts import PACK_SUBJECT_KIND, current_bind

if TYPE_CHECKING:
    from hpc_agent.state.pack import DerivedFrom, PackManifest

__all__ = ["program_init"]

_PRIMITIVE = "program-init"

#: The seam consumed to instantiate a program template at v1 (DC6). The
#: pinned/variable-section marker vocabulary + the pinned-verbatim check leg are
#: build-order item 3 of program-init.md — OUT of this unit.
_CONSUMED_SEAM = "audit_template"


def _resolve(experiment_dir: Path, relpath: str) -> Path:
    """Resolve a caller-referenced relpath against the experiment dir (bind posture)."""
    path = Path(relpath)
    return path if path.is_absolute() else experiment_dir / path


def _provenance_header(program: str, derived: DerivedFrom) -> str:
    """A code-authored comment header naming the lineage + init time (DC6).

    Prepended to the VERBATIM skeleton copy. This is provenance the human reads;
    core hashes the whole file (header + skeleton) as the program template's bytes,
    and records the SOURCE seam's sha (not this file's) in ``derived_from``.
    """
    return (
        "# ----------------------------------------------------------------------------\n"
        f"# PROGRAM TEMPLATE for {program!r} — generated by hpc-agent program-init.\n"
        "#\n"
        "# LINEAGE (derived_from, stamped mechanically — do NOT hand-edit; re-run\n"
        "# program-init/adopt over the real source to change it):\n"
        f"#   pack:    {derived.pack}\n"
        f"#   seam:    {derived.seam}\n"
        f"#   version: {derived.version}\n"
        f"#   sha:     {derived.sha}\n"
        f"#   init_at: {utcnow().isoformat()}\n"
        "#\n"
        "# The lines BELOW are a verbatim copy of the domain skeleton. Edit the\n"
        "# variable sections for this program; the pinned sections must survive so\n"
        "# the domain check passes (that check is build-order item 3, not this verb).\n"
        "# ----------------------------------------------------------------------------\n"
    )


def _load_domain(
    experiment_dir: Path, spec: ProgramInitSpec
) -> tuple[PackManifest, bytes, DerivedFrom]:
    """Load the domain manifest, read its ``audit_template`` seam, stamp the lineage.

    Loud :class:`errors.SpecInvalid` on a missing/invalid domain manifest, a domain
    manifest lacking an ``audit_template`` seam, or an unreadable seam file.
    """
    domain_manifest_path = _resolve(experiment_dir, spec.domain_manifest)
    domain = pack.load_manifest(domain_manifest_path)  # loud on missing/unreadable/bad
    seam_rel = domain.seams.get(_CONSUMED_SEAM)
    if not seam_rel:
        raise errors.SpecInvalid(
            f"domain manifest {str(domain_manifest_path)!r} declares no "
            f"{_CONSUMED_SEAM!r} seam — program-init consumes that seam to "
            "instantiate the program template"
        )
    seam_path = domain_manifest_path.parent / seam_rel
    try:
        skeleton_bytes = seam_path.read_bytes()
    except OSError as exc:
        raise errors.SpecInvalid(
            f"domain {_CONSUMED_SEAM!r} seam file {str(seam_path)!r} is unreadable "
            f"({exc}); cannot instantiate a program template from a vanished skeleton"
        ) from exc
    derived = pack.DerivedFrom(
        pack=domain.name,
        seam=_CONSUMED_SEAM,
        version=domain.version,
        sha=pack.sha256_bytes(skeleton_bytes),
    )
    return domain, skeleton_bytes, derived


def _check_interview_consistency(experiment_dir: Path, expected: dict[str, str]) -> None:
    """Refuse if interview.json binds a named pack to a CONTRADICTING manifest (DC9).

    ``program-init`` never writes interview.json (the interview primitive is the one
    writer). But when a packs block already exists, an entry for the domain or
    program pack that names a DIFFERENT manifest relpath than this init would use is
    a contradiction — a loud refusal, not a silent double source of truth.
    """
    for entry in read_packs_optin(experiment_dir):
        name = entry.get("pack")
        manifest_rel = entry.get("manifest")
        if (
            isinstance(name, str)
            and name in expected
            and isinstance(manifest_rel, str)
            and manifest_rel != expected[name]
        ):
            raise errors.SpecInvalid(
                f"interview.json packs block binds {name!r} to {manifest_rel!r}, "
                f"contradicting program-init's {expected[name]!r}; reconcile the "
                "opt-in block before adopting (init never rewrites interview.json)"
            )


def _bind(experiment_dir: Path, manifest_rel: str, pack_name: str) -> ProgramBind:
    """Bind a pack, reporting whether it was a RE-bind (a prior bind at a different sha)."""
    prior = current_bind(
        read_decisions(experiment_dir, PACK_SUBJECT_KIND, pack_name), pack=pack_name
    )
    result = pack_bind(
        experiment_dir=experiment_dir,
        spec=PackBindSpec(manifest=manifest_rel, pack=pack_name),
    )
    rebound = prior is not None and prior.manifest_sha != result.manifest_sha
    return ProgramBind(pack=pack_name, manifest_sha=result.manifest_sha, rebound=rebound)


def _create(
    experiment_dir: Path,
    spec: ProgramInitSpec,
    *,
    domain: PackManifest,
    skeleton_bytes: bytes,
    derived: DerivedFrom,
    program_manifest_rel: str,
) -> tuple[list[str], list[ProgramBind], str | None]:
    """Create mode: generate packs/<program>/ fresh, seal, bind both packs."""
    program = spec.program
    program_dir = experiment_dir / "packs" / program
    if program_dir.exists():
        raise errors.SpecInvalid(
            f"program-init create refuses to overwrite existing {str(program_dir)!r}; "
            "use mode='adopt' to migrate an existing program pack onto its lineage"
        )

    template_rel = spec.template_relpath or f"packs/{program}/templates/{program}_audit.py"
    template_path = experiment_dir / template_rel
    # The template's relpath WITHIN the program pack root (manifest seams + recipe
    # pack_files are pack-root-relative).
    template_rel_in_pack = os.path.relpath(template_path, program_dir).replace(os.sep, "/")

    # VERBATIM skeleton copy + code-authored provenance header (DC6). Raw bytes:
    # core never rewrites template content; the skeleton is copied byte-for-byte.
    template_path.parent.mkdir(parents=True, exist_ok=True)
    template_path.write_bytes(_provenance_header(program, derived).encode("utf-8") + skeleton_bytes)

    # The recipe is the DURABLE lineage stamp (DC3); the generic reseal copies it
    # into the manifest. Program version inherits the domain version at init (an
    # opaque echo — ORDERING is the sha's job).
    recipe = {
        "name": program,
        "version": domain.version,
        "seams": {_CONSUMED_SEAM: template_rel_in_pack},
        "fills_slots": [],
        "pack_files": [template_rel_in_pack],
        "sweep": [],
        "derived_from": {
            "pack": derived.pack,
            "seam": derived.seam,
            "version": derived.version,
            "sha": derived.sha,
        },
    }
    program_dir.mkdir(parents=True, exist_ok=True)
    recipe_path = program_dir / pack_sweep.RECIPE_FILENAME
    atomic_write_text(recipe_path, json.dumps(recipe, indent=2) + "\n")

    manifest_path = program_dir / "manifest.json"
    pack_sweep.reseal_manifest(manifest_path, recipe_path)

    created = [
        template_rel,
        f"packs/{program}/{pack_sweep.RECIPE_FILENAME}",
        program_manifest_rel,
    ]

    binds: list[ProgramBind] = []
    if spec.bind:
        binds.append(_bind(experiment_dir, spec.domain_manifest, domain.name))
        binds.append(_bind(experiment_dir, program_manifest_rel, program))

    note = (
        "pack-status stays empty until the interview persists packs_optin; confirm "
        "this init via read-decisions or this result, not pack-status"
    )
    return created, binds, note


def _adopt(
    experiment_dir: Path,
    spec: ProgramInitSpec,
    *,
    derived: DerivedFrom,
    program_manifest_rel: str,
) -> tuple[list[str], list[ProgramBind], str | None]:
    """Adopt mode: stamp lineage onto an existing program pack WITHOUT touching content."""
    program = spec.program
    program_dir = experiment_dir / "packs" / program
    if not program_dir.is_dir():
        raise errors.SpecInvalid(
            f"program-init adopt requires an existing {str(program_dir)!r} directory; "
            "use mode='create' to generate a new program pack"
        )
    recipe_path = program_dir / pack_sweep.RECIPE_FILENAME
    if not recipe_path.is_file():
        raise errors.SpecInvalid(
            f"program-init adopt requires an existing {pack_sweep.RECIPE_FILENAME} "
            f"recipe beside {str(program_dir / 'manifest.json')!r}; core cannot "
            "generically re-seal a program pack without its declarative recipe"
        )

    # Stamp the recipe (raw read-modify-write, unknown keys preserved) THEN reseal —
    # the reseal copies the stamp into the manifest. NO content file is written: the
    # signed template stays byte-identical (memo hazard 2).
    pack_sweep.stamp_recipe_derived_from(recipe_path, derived)
    manifest_path = program_dir / "manifest.json"
    outcome = pack_sweep.reseal_manifest(manifest_path, recipe_path)

    # Rebind ONLY the program pack (the one whose manifest bytes moved). The domain
    # pack is a lineage root — its bytes never change here — so rebinding it would be
    # a no-op rebind at the same sha; adopt leaves it untouched (premortem ruling).
    binds: list[ProgramBind] = []
    if spec.bind and outcome.wrote:
        binds.append(_bind(experiment_dir, program_manifest_rel, program))

    note = (
        "adopt stamped the recipe + resealed the manifest without byte-changing any "
        "content file; only the program pack was rebound (the domain root is "
        "untouched). The prior bind's covered receipts now read stale — re-earn them "
        "(zero re-sign-offs: sign-offs bind section-body x template identity, both "
        "unchanged)."
    )
    return [], binds, note


def _check_and_slots(
    experiment_dir: Path,
    spec: ProgramInitSpec,
    *,
    domain: PackManifest,
    optin: list[dict[str, Any]],
) -> tuple[bool, bool | None, list[ProgramSlotToEarn]]:
    """Run a caller-resolvable check, else report the domain slots as to-earn (DC7)."""
    if spec.check:
        run = run_check_command(spec.check, cwd=experiment_dir, timeout_sec=check_timeout_sec())
        append_jsonl_line(
            pack_checks_log_path(experiment_dir, spec.program),
            {
                "at": utcnow().isoformat(),
                "pack": spec.program,
                "slot": None,
                "check": spec.check,
                "argv": run.argv,
                "exit_code": run.exit_code,
                "timed_out": run.timed_out,
                "spawn_error": run.spawn_error,
                "ok": run.ok,
                "stdout_tail": run.stdout_tail,
                "stderr_tail": run.stderr_tail,
            },
        )
        return True, run.ok, []

    # No resolvable command → report the domain pack's receipt slots to earn, each
    # with its caller-side check command (from the opt-in) when the caller recorded
    # one. Core never composes an argv from pack content (DP2).
    checks = slot_check_commands(optin)
    slots = [
        ProgramSlotToEarn(slot=slot, pack=domain.name, check=checks.get((domain.name, slot)))
        for slot in domain.fills_slots
    ]
    return False, None, slots


@primitive(
    name=_PRIMITIVE,
    verb="mutate",
    side_effects=[
        SideEffect("file_write", "<experiment>/packs/<program>/**"),
        SideEffect("file_write", "<experiment>/.hpc/packs/<pack>.decisions.jsonl"),
    ],
    error_codes=[errors.SpecInvalid],
    # Not idempotent: create writes fresh files + appends binds; adopt reseals +
    # appends a rebind. A second create over an existing program dir REFUSES.
    idempotent=False,
    cli=CliShape(
        help=(
            "Materialize (create) or migrate (adopt) a PROGRAM pack layer from a "
            "domain pack's audit_template seam: instantiate the program template "
            "(verbatim skeleton copy + provenance header in create mode; untouched "
            "in adopt mode), stamp the derived_from lineage MECHANICALLY into the "
            "sweep.json recipe, seal the manifest via the generic pack re-seal, and "
            "bind the packs (journaling old→new). Core never interprets template "
            "content and never composes a check argv from pack content — a "
            "caller-authored check (spec.check) is run in the experiment dir, else "
            "the domain receipt slots are reported as to-earn. Pure local read + "
            "file write + journal append, no SSH."
        ),
        spec_arg=True,
        experiment_dir_arg=True,
        spec_model=ProgramInitSpec,
        schema_ref=SchemaRef(input="program_init"),
    ),
    agent_facing=True,
)
def program_init(*, experiment_dir: Path, spec: ProgramInitSpec) -> ProgramInitResult:
    """Create or adopt a program pack layer; stamp lineage, seal, bind.

    Loud :class:`errors.SpecInvalid` on: a missing/invalid domain manifest; a domain
    manifest with no ``audit_template`` seam; create over an existing program dir;
    adopt over a missing program dir/recipe; or an interview packs block that
    contradicts this init. A failing caller check is REPORTED (``check_ok=False``),
    never raised.
    """
    experiment_dir = Path(experiment_dir)
    program = spec.program
    program_manifest_rel = f"packs/{program}/manifest.json"

    domain, skeleton_bytes, derived = _load_domain(experiment_dir, spec)

    _check_interview_consistency(
        experiment_dir,
        {domain.name: spec.domain_manifest, program: program_manifest_rel},
    )

    if spec.mode == "create":
        created, binds, note = _create(
            experiment_dir,
            spec,
            domain=domain,
            skeleton_bytes=skeleton_bytes,
            derived=derived,
            program_manifest_rel=program_manifest_rel,
        )
    else:
        created, binds, note = _adopt(
            experiment_dir,
            spec,
            derived=derived,
            program_manifest_rel=program_manifest_rel,
        )

    optin = read_packs_optin(experiment_dir)
    check_ran, check_ok, slots_to_earn = _check_and_slots(
        experiment_dir, spec, domain=domain, optin=optin
    )

    packs_optin = [
        PackOptInEcho(
            pack=domain.name,
            manifest=spec.domain_manifest,
            receipt_bindings=[
                ReceiptBindingEcho(slot=slot, pack=domain.name) for slot in domain.fills_slots
            ],
        ),
        PackOptInEcho(pack=program, manifest=program_manifest_rel, receipt_bindings=[]),
    ]

    return ProgramInitResult(
        program=program,
        mode=spec.mode,
        derived_from=DerivedFromEcho(
            pack=derived.pack, seam=derived.seam, version=derived.version, sha=derived.sha
        ),
        created_files=created,
        binds=binds,
        check_ran=check_ran,
        check_ok=check_ok,
        slots_to_earn=slots_to_earn,
        packs_optin=packs_optin,
        note=note,
    )
