# ruff: noqa: E501 — generated dict literal; one (verb, module) row per line.
"""Generated verb → defining-module map for the CLI single-verb fast path.

DO NOT EDIT BY HAND. Regenerate with::

    uv run python scripts/build_verb_module_map.py --write

Maps each ungrouped, handler-less verb to ``(primitive_name, module_path)`` so
``hpc_agent.cli.dispatch.main`` can import only that module (instead of the full
``register_primitives`` walk) before dispatching it. Self-healing: a stale entry
just falls back to the full path. See ``scripts/build_verb_module_map.py``.
"""

from __future__ import annotations

VERB_MODULE_MAP: dict[str, tuple[str, str]] = {
    'aggregate-check': ('aggregate-check', 'hpc_agent.ops.aggregate_blocks'),
    'aggregate-flow': ('aggregate-flow', 'hpc_agent.ops.aggregate_flow'),
    'aggregate-preflight': ('aggregate-preflight', 'hpc_agent.ops.aggregate_preflight'),
    'aggregate-run': ('aggregate-run', 'hpc_agent.ops.aggregate_blocks'),
    'append-decision': ('append-decision', 'hpc_agent.ops.decision.journal'),
    'apply-safe-defaults': ('apply-safe-defaults', 'hpc_agent.ops.submit.apply_safe_defaults'),
    'archive-dossier': ('archive-dossier', 'hpc_agent.ops.archive_dossier'),
    'attention-queue': ('attention-queue', 'hpc_agent.ops.attention_op'),
    'audit-handoff': ('audit-handoff', 'hpc_agent.ops.notebook.audit_handoff_op'),
    'audit-preflight': ('audit-preflight', 'hpc_agent.ops.audit_preflight'),
    'axes-init': ('axes-init', 'hpc_agent.incorporation.axes_init'),
    'batch-status': ('batch-status', 'hpc_agent.ops.monitor.batch_status'),
    'block-drive': ('block-drive', 'hpc_agent.ops.block_drive_op'),
    'build-executor': ('build-executor', 'hpc_agent.incorporation.build.executor'),
    'build-submit-spec': ('build-submit-spec', 'hpc_agent.incorporation.build.submit_spec'),
    'build-tasks-py': ('build-tasks-py', 'hpc_agent.incorporation.build.tasks_py'),
    'build-template': ('build-template', 'hpc_agent.incorporation.build.template'),
    'campaign-complete': ('campaign-complete', 'hpc_agent.meta.campaign.blocks'),
    'campaign-greenlight': ('campaign-greenlight', 'hpc_agent.meta.campaign.blocks'),
    'campaign-refill': ('campaign-refill', 'hpc_agent.ops.campaign_refill'),
    'campaign-run': ('campaign-run', 'hpc_agent.ops.campaign_run'),
    'campaign-watch': ('campaign-watch', 'hpc_agent.meta.campaign.blocks'),
    'challenge-status': ('challenge-status', 'hpc_agent.ops.challenge_status_op'),
    'check-task-generator-mismatch': ('check-task-generator-mismatch', 'hpc_agent.ops.check_task_generator_mismatch'),
    'classify-axis': ('classify-axis', 'hpc_agent.incorporation.classify_axis'),
    'classify-axis-auto': ('classify-axis-auto', 'hpc_agent.incorporation.classify_axis_auto'),
    'classify-axis-easy': ('classify-axis-easy', 'hpc_agent.incorporation.classify_axis_easy'),
    'classify-axis-preflight': ('classify-axis-preflight', 'hpc_agent.ops.classify_axis_preflight'),
    'classify-campaign-path': ('classify-campaign-path', 'hpc_agent.incorporation.classify_campaign_path'),
    'cluster-reduce': ('cluster-reduce', 'hpc_agent.ops.aggregate.cluster_reduce'),
    'compute-run-id': ('compute-run-id', 'hpc_agent.incorporation.build.compute_run_id'),
    'conformance-record': ('conformance-record', 'hpc_agent.ops.conformance.record_op'),
    'conformance-status': ('conformance-status', 'hpc_agent.ops.conformance.status_op'),
    'dag-frontier': ('dag-frontier', 'hpc_agent.ops.dag_frontier'),
    'data-manifest': ('data-manifest', 'hpc_agent.ops.data_manifest'),
    'decide-concurrency': ('decide-concurrency', 'hpc_agent.meta.campaign.atoms.decide_concurrency'),
    'decide-monitor-arm': ('decide-monitor-arm', 'hpc_agent.ops.monitor.arm'),
    'decide-partial-handling': ('decide-partial-handling', 'hpc_agent.ops.aggregate.decide_partial_handling'),
    'decide-resubmit': ('decide-resubmit', 'hpc_agent.ops.decide_resubmit'),
    'decorate-entry-point': ('decorate-entry-point', 'hpc_agent.incorporation.decorate_entry_point'),
    'detect-entry-point': ('detect-entry-point', 'hpc_agent.ops.detect_entry_point'),
    'dir-digest': ('dir-digest', 'hpc_agent.ops.dir_digest'),
    'discover': ('discover-executors', 'hpc_agent.state.discover'),
    'discover-reducers': ('discover-reducers', 'hpc_agent.state.discover'),
    'discover-runs': ('discover-runs', 'hpc_agent.state.discover'),
    'doctor': ('doctor', 'hpc_agent.ops.recover.doctor'),
    'doctor-install': ('doctor-install', 'hpc_agent.ops.recover.doctor_install'),
    'evidence-brief': ('evidence-brief', 'hpc_agent.ops.evidence_brief_op'),
    'evidence-period': ('evidence-period', 'hpc_agent.ops.evidence_period_op'),
    'export-attestations': ('export-attestations', 'hpc_agent.ops.export_attestations'),
    'export-dossier': ('export-dossier', 'hpc_agent.ops.export_dossier'),
    'export-package': ('export-package', 'hpc_agent.incorporation.export_package'),
    'failures': ('failures', 'hpc_agent.ops.recover.failures_atom'),
    'find-prior-run': ('find-prior-run', 'hpc_agent.cli.setup_actions'),
    'harness-capabilities': ('harness-capabilities', 'hpc_agent.ops.harness_capabilities'),
    'host-retarget': ('host-retarget', 'hpc_agent.ops.host_retarget'),
    'inspect-deployment': ('inspect-deployment', 'hpc_agent.ops.inspect_deployment'),
    'inspect-parallel-axes': ('inspect-parallel-axes', 'hpc_agent.ops.inspect_parallel_axes'),
    'interview': ('interview', 'hpc_agent.ops.memory.interview'),
    'kill': ('kill', 'hpc_agent.ops.monitor.kill'),
    'list-in-flight': ('list-in-flight', 'hpc_agent.ops.monitor.list_in_flight'),
    'load-context': ('load-context', 'hpc_agent.meta.campaign.atoms.load_context'),
    'logs': ('logs', 'hpc_agent.ops.monitor.logs_atom'),
    'monitor-flow': ('monitor-flow', 'hpc_agent.ops.monitor_flow'),
    'monitor-summary': ('monitor-summary', 'hpc_agent.ops.monitor.summary'),
    'net-triage': ('net-triage', 'hpc_agent.ops.recover.net_triage'),
    'notebook-audit-view': ('notebook-audit-view', 'hpc_agent.ops.notebook.view_op'),
    'notebook-auto-clear': ('notebook-auto-clear', 'hpc_agent.ops.notebook.auto_clear_op'),
    'notebook-draft': ('notebook-draft', 'hpc_agent.ops.notebook.draft_op'),
    'notebook-draft-context': ('notebook-draft-context', 'hpc_agent.ops.notebook.draft_context_op'),
    'notebook-lint': ('notebook-lint', 'hpc_agent.ops.notebook.lint'),
    'notebook-record-config': ('notebook-record-config', 'hpc_agent.ops.notebook.record_config_op'),
    'notebook-record-receipt': ('notebook-record-receipt', 'hpc_agent.ops.notebook.record_receipt_op'),
    'notebook-scaffold-template': ('notebook-scaffold-template', 'hpc_agent.ops.notebook.scaffold_template_op'),
    'notebook-status': ('notebook-status', 'hpc_agent.ops.notebook.status_op'),
    'pack-bind': ('pack-bind', 'hpc_agent.ops.pack.bind_op'),
    'pack-record-receipt': ('pack-record-receipt', 'hpc_agent.ops.pack.record_receipt_op'),
    'pack-refresh': ('pack-refresh', 'hpc_agent.ops.pack.refresh_op'),
    'pack-status': ('pack-status', 'hpc_agent.ops.pack.status_op'),
    'plan-throughput': ('plan-throughput', 'hpc_agent.ops.submit.plan_throughput'),
    'preflight': ('check-preflight', 'hpc_agent.ops.preflight.check'),
    'prepare-followup-specs': ('prepare-followup-specs', 'hpc_agent.ops.prepare_followup_specs'),
    'prepare-phase2-spec': ('prepare-phase2-spec', 'hpc_agent.ops.prepare_phase2_spec'),
    'provenance-manifest': ('provenance-manifest', 'hpc_agent.ops.provenance_manifest'),
    'read-decisions': ('read-decisions', 'hpc_agent.ops.decision.journal'),
    'recall': ('recall', 'hpc_agent.ops.memory.recall'),
    'recommend-partition': ('recommend-partition', 'hpc_agent.ops.submit.recommend_partition'),
    'reconcile': ('reconcile-journal', 'hpc_agent.ops.monitor.reconcile'),
    'reconcile-stale': ('reconcile-stale', 'hpc_agent.ops.monitor.reconcile_stale'),
    'reproduce-run': ('reproduce-run', 'hpc_agent.ops.reproduce_run'),
    'resolve-resources': ('resolve-resources', 'hpc_agent.ops.resolve_resources'),
    'resolve-submit-inputs': ('resolve-submit-inputs', 'hpc_agent.ops.resolve_submit_inputs'),
    'retarget-run': ('retarget-run', 'hpc_agent.ops.retarget_run'),
    'revise-resolved': ('revise-resolved', 'hpc_agent.ops.revise_resolved'),
    'run-story': ('run-story', 'hpc_agent.ops.run_story'),
    'scaffold-spec': ('scaffold-spec', 'hpc_agent.ops.scaffold_spec'),
    'scaffold-strategy': ('scaffold-strategy', 'hpc_agent.incorporation.scaffold_strategy'),
    'scope-lock': ('scope-lock', 'hpc_agent.ops.decision.scope_lock'),
    'scope-status': ('scope-status', 'hpc_agent.ops.decision.scope_lock'),
    'settle-run': ('settle-run', 'hpc_agent.ops.settle_run'),
    'smoke-test-executor': ('smoke-test-executor', 'hpc_agent.ops.smoke_test_executor'),
    'status-pipeline': ('status-pipeline', 'hpc_agent.ops.status_pipeline'),
    'status-preflight': ('status-preflight', 'hpc_agent.ops.status_preflight'),
    'status-snapshot': ('status-snapshot', 'hpc_agent.ops.status_blocks'),
    'status-watch': ('status-watch', 'hpc_agent.ops.status_blocks'),
    'stray-sweep': ('stray-sweep', 'hpc_agent.ops.recover.stray_sweep'),
    'submit-and-verify': ('submit-and-verify', 'hpc_agent.ops.submit_and_verify'),
    'submit-pipeline': ('submit-pipeline', 'hpc_agent.ops.submit_pipeline'),
    'submit-preflight': ('submit-preflight', 'hpc_agent.ops.submit_preflight'),
    'submit-s1': ('submit-s1', 'hpc_agent.ops.submit_blocks'),
    'submit-s2': ('submit-s2', 'hpc_agent.ops.submit_blocks'),
    'submit-s3': ('submit-s3', 'hpc_agent.ops.submit_blocks'),
    'submit-s4': ('submit-s4', 'hpc_agent.ops.submit_blocks'),
    'submit-speculate': ('submit-speculate', 'hpc_agent.ops.submit_speculate'),
    'suggest-setup-action': ('suggest-setup-action', 'hpc_agent.cli.setup_actions'),
    'summarize-submit-plan': ('summarize-submit-plan', 'hpc_agent.ops.submit.plan_summary'),
    'trace': ('trace', 'hpc_agent.ops.trace'),
    'trace-diff': ('trace-diff', 'hpc_agent.ops.trace_diff_op'),
    'trace-render': ('trace-render', 'hpc_agent.ops.trace_render_op'),
    'update-run-constraints': ('update-run-constraints', 'hpc_agent.ops.monitor.update_constraints'),
    'validate-campaign': ('validate-campaign', 'hpc_agent.meta.validate_campaign'),
    'verify-aggregation-complete': ('verify-aggregation-complete', 'hpc_agent.ops.aggregate.invariants'),
    'verify-canary': ('verify-canary', 'hpc_agent.ops.verify_canary'),
    'verify-registration': ('verify-registration', 'hpc_agent.ops.registration.verify_op'),
    'verify-relay': ('verify-relay', 'hpc_agent.ops.decision.verify_relay'),
    'verify-reproduction': ('verify-reproduction', 'hpc_agent.ops.verify_reproduction'),
    'verify-submitted': ('verify-submitted', 'hpc_agent.ops.verify_submitted'),
    'wait-detached': ('wait-detached', 'hpc_agent.ops.monitor.wait_detached'),
    'walk-submit-ambiguities': ('walk-submit-ambiguities', 'hpc_agent.ops.walk_submit_ambiguities'),
    'watcher-install': ('watcher-install', 'hpc_agent.ops.monitor.watcher_install'),
    'worker-log-digest': ('worker-log-digest', 'hpc_agent.ops.worker_log_digest'),
    'write-run-sidecar': ('write-run-sidecar', 'hpc_agent.ops.write_run_sidecar'),
}
