"""Executor-side CLI helpers — the building blocks for ``.hpc/`` glue.

Static framework module. Provides:

- :class:`Flag` and the :func:`flag` constructor — declarative spec for one
  argparse argument.
- :func:`generic_args` and :func:`gpu_args` — pre-built flag lists every
  executor and every GPU executor commonly needs.
- :func:`build_parser_from_flags` — turns a flag list into an
  :class:`argparse.ArgumentParser`.

The auto-generated ``.hpc/tasks.py`` declares a per-executor FLAGS dict
keyed by importable module path:

.. code-block:: python

    # .hpc/tasks.py — auto-generated by /submit-hpc Step 6
    from hpc_mapreduce.executor_cli import flag, generic_args, gpu_args

    FLAGS = {
        "src.ml_ridge":   [*generic_args(), flag("horizon", int, default=1)],
        "src.dl_patchts": [*generic_args(), *gpu_args(), flag("horizon", int)],
    }

    def resolve(task_id): ...
    def total(): ...

The matching ``.hpc/cli.py`` (also auto-generated, never hand-edited)
loads tasks.py, looks up the right FLAGS list per executor module, and
dispatches to ``compute(args)``:

.. code-block:: python

    # python -m cli src.ml_ridge --horizon 1 --output-file out.csv
    executor_module = sys.argv.pop(1)
    args = get_parser(executor_module).parse_args()
    importlib.import_module(executor_module).compute(args)

**The one cross-experiment convention:** every executor module exports
``compute(args) -> None``. The dispatcher hard-codes that name.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class Flag:
    """Declarative spec for one argparse flag.

    Names use Python identifier style (underscores). The CLI flag is
    produced as ``--{name.replace("_", "-")}``; argparse normalizes the
    parsed attribute back to ``args.{name}``.
    """

    name: str
    type: type | None = str
    default: Any = None
    required: bool = False
    choices: tuple[Any, ...] | None = None
    help: str = ""
    nargs: str | None = None

    def add_to(self, parser: argparse.ArgumentParser) -> None:
        kwargs: dict[str, Any] = {"help": self.help}
        if self.required:
            kwargs["required"] = True
        if self.default is not None:
            kwargs["default"] = self.default
        elif not self.required:
            # Explicit None default for optional flags; lets executors
            # do `if args.foo is not None:` reliably.
            kwargs["default"] = None
        if self.choices is not None:
            kwargs["choices"] = list(self.choices)
        if self.nargs is not None:
            kwargs["nargs"] = self.nargs
        if self.type is not None:
            kwargs["type"] = self.type
        cli_flag = "--" + self.name.replace("_", "-")
        parser.add_argument(cli_flag, **kwargs)


def flag(
    name: str,
    type: type | None = str,
    *,
    default: Any = None,
    required: bool = False,
    choices: tuple[Any, ...] | list[Any] | None = None,
    help: str = "",
    nargs: str | None = None,
) -> Flag:
    """Concise constructor for a :class:`Flag` declaration."""
    return Flag(
        name=name,
        type=type,
        default=default,
        required=required,
        choices=tuple(choices) if choices is not None else None,
        help=help,
        nargs=nargs,
    )


def generic_args() -> list[Flag]:
    """Common flags every executor accepts.

    ``--output-file`` is the only contract requirement. The rest are
    common enough across experiment domains (windowing, RNG seed, data
    path) that defaulting to inclusion is more useful than not.
    Experiments that don't use ``--start``/``--end``/``--data-path``
    just ignore the parsed values.
    """
    return [
        flag(
            "output_file",
            str,
            required=True,
            help="Where to write executor results (per-task output path).",
        ),
        flag("seed", int, default=42, help="Random seed for deterministic reproduction."),
        flag(
            "start",
            int,
            default=0,
            help="Window start index/offset (interpretation is executor-specific).",
        ),
        flag(
            "end",
            int,
            default=-1,
            help="Window end index/offset (-1 = to end).",
        ),
        flag(
            "data_path",
            str,
            help="Path to input data (interpretation is executor-specific).",
        ),
    ]


def gpu_args() -> list[Flag]:
    """Common flags for GPU/DL executors.

    Add alongside :func:`generic_args` for any executor that runs on
    GPU. ``--epochs`` / ``--batch-size`` / ``--learning-rate`` default
    to None so each method can fall back to its own internal default
    while still being grid-overrideable from ``.hpc/tasks.py``.
    """
    return [
        flag("gpu_count", int, default=1, help="Number of GPUs to use."),
        flag("epochs", int, help="Training epochs (None = method-specific default)."),
        flag("batch_size", int, help="Training batch size (None = method-specific default)."),
        flag("learning_rate", float, help="Learning rate (None = method-specific default)."),
    ]


def build_parser_from_flags(
    flags: list[Flag] | list[dict[str, Any]],
    *,
    description: str = "",
) -> argparse.ArgumentParser:
    """Build an :class:`argparse.ArgumentParser` from a declarative flag list.

    Each entry may be a :class:`Flag` instance (preferred) or a dict
    with the same keys. The returned parser is ready to
    ``.parse_args(argv)``.
    """
    parser = argparse.ArgumentParser(description=description)
    for f in flags:
        if isinstance(f, Flag):
            f.add_to(parser)
        elif isinstance(f, dict):
            Flag(**f).add_to(parser)
        else:
            raise TypeError(
                f"FLAGS entries must be Flag instances or dicts; got {type(f).__name__}"
            )
    return parser
