"""Wrapper materializer for the interview's ``shell_command`` entry point.

A mature repo arriving with ``main.py`` (and optional frozen YAML
configs) declares its entry point as
``{kind: "shell_command", argv: [...], signature: {...}, frozen_configs: [...]}``
on ``interview.json``. This module materializes a thin Python wrapper at
``<campaign_dir>/.hpc/wrappers/<run_name>.py`` whose body
subprocess-invokes the argv with kwargs substituted in.

The wrapper exists to give the framework something to introspect:

* ``@register_run`` for ``discover_runs`` and the cluster runtime
* a typed function signature for ``validate-executor-signatures``
* a hashable identity (``run_signature_sha``) for drift detection

``main.py`` itself stays opaque and untouched.

``frozen_configs`` are hashed; the interview threads the resulting
``<basename>_sha`` fields into every materialized task's kwargs so
``cmd_sha`` distinguishes two different YAML files (and catches an
accidental in-place edit).

This module is framework-internal setup tooling: it lives in
``incorporation/`` because it materializes a runtime artifact, and the
artifact imports ``@register_run`` from :mod:`hpc_agent.experiment_kit`
— preserving the one-direction dependency ``incorporation/`` →
``experiment_kit/``.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import TYPE_CHECKING

from hpc_agent import errors

if TYPE_CHECKING:
    from collections.abc import Mapping


__all__ = [
    "materialize_shell_wrapper",
    "register_run_executor_cmd",
    "WrapperResult",
    "wrapper_executor_cmd",
]


_WRAPPERS_SUBDIR = Path(".hpc") / "wrappers"

# Auto-generated header — every materialized wrapper carries this docstring so
# operators reading the file know it's framework-managed.
_HEADER = '''"""Auto-generated by ``hpc-agent interview`` from intent.entry_point.

Do not edit by hand. The interview regenerates this file from the
declared argv + signature each time intent.entry_point changes. To
diverge from the wrapper pattern, drop ``entry_point`` from the next
intent.json and supply a hand-written ``@register_run`` notebook
instead.
"""
from __future__ import annotations

import subprocess
from hpc_agent.experiment_kit import register_run
'''


class WrapperResult:
    """Outcome of materializing a shell_command wrapper.

    Light value type, not a Pydantic model, because it's an
    internal interview-primitive return — not a wire surface.
    """

    __slots__ = ("wrapper_path", "frozen_shas")

    def __init__(self, wrapper_path: Path, frozen_shas: Mapping[str, str]) -> None:
        self.wrapper_path = wrapper_path
        # dict copy so the caller cannot mutate our internal state.
        self.frozen_shas: dict[str, str] = dict(frozen_shas)


def materialize_shell_wrapper(
    *,
    campaign_dir: Path,
    run_name: str,
    argv: list[str],
    signature: Mapping[str, str],
    frozen_configs: list[str],
) -> WrapperResult:
    """Write ``<campaign_dir>/.hpc/wrappers/<run_name>.py`` and hash frozen configs.

    Pure: same inputs produce the same file bytes (modulo no timestamps
    embedded). Idempotent: re-running with the same inputs overwrites
    byte-equivalently. The caller (``record_interview``) controls atomic
    semantics by deciding when to invoke this.

    Returns a :class:`WrapperResult` carrying the wrapper path and a
    ``{basename_sha: hex_digest}`` mapping the interview threads into
    tasks-kwargs for identity (``cmd_sha`` inclusion).

    Raises :class:`errors.SpecInvalid` when a frozen config path is
    missing or escapes the campaign_dir; the interview surfaces this as
    spec_invalid at the wire boundary.
    """
    # Hash frozen configs first — if any path is invalid, fail before
    # touching the filesystem so a bad spec leaves no residue (no empty
    # wrappers/ dir, no half-written wrapper file pointing at a missing
    # config). Atomicity matters here because the caller surfaces the
    # error via the spec_invalid envelope.
    frozen_shas = _hash_frozen_configs(campaign_dir, frozen_configs)

    wrappers_dir = campaign_dir / _WRAPPERS_SUBDIR
    wrappers_dir.mkdir(parents=True, exist_ok=True)

    body = _render_wrapper_body(run_name=run_name, argv=argv, signature=signature)
    wrapper_path = wrappers_dir / f"{run_name}.py"
    content = _HEADER + "\n" + body
    # Idempotency: skip the write when bytes are identical so an mtime-
    # sensitive consumer (or just a curious operator running `ls -la`)
    # doesn't see churn on a no-op re-run. The body has no timestamps,
    # so any byte difference here means the spec actually changed.
    if not wrapper_path.is_file() or wrapper_path.read_text(encoding="utf-8") != content:
        wrapper_path.write_text(content, encoding="utf-8")

    return WrapperResult(wrapper_path=wrapper_path, frozen_shas=frozen_shas)


def wrapper_executor_cmd(
    *,
    campaign_dir: Path,
    run_name: str,
) -> str:
    """Return the shell command to invoke ``<run_name>``'s wrapper on a task.

    The materialized wrapper is a Python module with ``@register_run``
    that injects a ``compute(args)`` callable into its namespace. The
    cluster-side dispatcher exports each kwarg from ``tasks.resolve(i)``
    as both ``HPC_KW_<NAME>`` and bare ``<NAME>`` env vars, then runs
    this shell command per task. The one-liner builds an ``args``
    namespace from those env vars and dispatches.

    Returned form is a shell command suitable for stamping into the
    submit-flow spec / sidecar's ``executor`` field; ``submit-flow``
    consumes it as-is.

    Note: assumes the wrapper has already been materialized at
    ``<campaign_dir>/.hpc/wrappers/<run_name>.py``. The helper just
    composes the command — it neither writes nor verifies the wrapper.
    """
    rel = _WRAPPERS_SUBDIR / f"{run_name}.py"
    # Single-quote-safe Python one-liner: import the materialized module by
    # path (no package install required on the cluster), build args from
    # HPC_KW_* env vars, then call compute(args). The dispatcher's bare-
    # form env exports (NAME alongside HPC_KW_NAME) aren't used here — the
    # HPC_KW_* namespace is the stable contract.
    #
    # rel.as_posix(): this command runs on the Linux cluster, so the embedded
    # path must use forward slashes even when the campaign was authored on
    # Windows (str(WindowsPath) would bake in backslashes that break the
    # cluster-side os.path.join lookup).
    py = (
        "import argparse,importlib.util,os,sys;"
        f"_p=os.path.join(os.environ.get('REPO_DIR','.'), {rel.as_posix()!r});"
        "_s=importlib.util.spec_from_file_location('_hpc_wrapper',_p);"
        "_m=importlib.util.module_from_spec(_s);_s.loader.exec_module(_m);"
        "_n=argparse.Namespace(**{k[len('HPC_KW_'):].lower():v "
        "for k,v in os.environ.items() if k.startswith('HPC_KW_')});"
        "_m.compute(_n)"
    )
    return f'python3 -c "{py}"'


def register_run_executor_cmd(
    *,
    campaign_dir: Path,
    run_path: Path,
) -> str:
    """Return the shell command to invoke a ``@register_run``-decorated
    function in the user's existing file on a task.

    Mirror of :func:`wrapper_executor_cmd` for the **direct-decoration**
    case — where the user's existing executor file carries
    ``@register_run`` (as opposed to a materialized wrapper at
    ``.hpc/wrappers/<run_name>.py`` for the shell_command fallback).

    The ``@register_run`` decorator injects ``compute(args)`` into the
    module's namespace at decoration time. The one-liner imports the
    user's file by path, builds an ``args`` Namespace from ``HPC_KW_*``
    env vars exported by the cluster dispatcher, and calls
    ``compute(args)`` — which the decorator's wrapper then routes
    through the user's function and writes the dict result to
    ``args.output_file`` if one was provided.

    Without this helper, the framework would naively use
    ``python3 <run_path>`` as the executor command; the dispatcher
    passes kwargs only as env vars (never argv), so a file whose
    ``__main__`` block uses argparse would fail with "required argument
    missing" — and a file without a ``__main__`` block would silently
    exit 0 without invoking ``compute``. Both empirical cases observed
    in live demos.

    *run_path* must be a path inside *campaign_dir*; the embedded
    POSIX relative form ships with the campaign rsync and is resolved
    against ``$REPO_DIR`` at task time, matching the wrapper case.
    """
    rel = run_path.relative_to(campaign_dir).as_posix()
    # Default ``output_file`` to ``$RESULT_DIR/metrics.json`` so a
    # user function that just ``return``s a dict (the common
    # @register_run pattern) actually lands the result on disk. The
    # decorator-injected ``compute(args)`` writes the dict to
    # ``args.output_file`` when both are present — without this
    # ``setdefault``, the dispatcher exports ``RESULT_DIR`` but no
    # ``HPC_KW_OUTPUT_FILE`` (the dispatcher's HPC_KW_* contract
    # carries only ``tasks.resolve(i)`` kwargs, never framework
    # metadata), so the dict is silently dropped. Empirical 0.10.3
    # demo: 100 tasks ran, only ``_runtime.json`` written, no
    # ``metrics.json``. The explicit user-supplied output_file (via
    # FLAGS / argparse) still wins because it lands as
    # ``HPC_KW_OUTPUT_FILE`` and the dict comprehension picks it up
    # before the setdefault fires.
    py = (
        "import argparse,importlib.util,os;"
        f"_p=os.path.join(os.environ.get('REPO_DIR','.'), {rel!r});"
        "_s=importlib.util.spec_from_file_location('_hpc_run',_p);"
        "_m=importlib.util.module_from_spec(_s);_s.loader.exec_module(_m);"
        "_kw={k[len('HPC_KW_'):].lower():v "
        "for k,v in os.environ.items() if k.startswith('HPC_KW_')};"
        "_kw.setdefault('output_file', "
        "os.path.join(os.environ.get('RESULT_DIR','.'), 'metrics.json'));"
        "_n=argparse.Namespace(**_kw);"
        "_m.compute(_n)"
    )
    return f'python3 -c "{py}"'


def _hash_frozen_configs(campaign_dir: Path, frozen_configs: list[str]) -> dict[str, str]:
    """Resolve each path against *campaign_dir*, hash its bytes, derive a kwarg name.

    The kwarg name is ``<filename_stem>_sha`` — e.g. ``configs/exp_42.yaml``
    becomes ``exp_42_sha``. Collisions (two configs with the same stem)
    are rejected: the interview can't thread two different shas under
    the same kwarg.
    """
    shas: dict[str, str] = {}
    for rel in frozen_configs:
        if not rel:
            raise errors.SpecInvalid("frozen_configs entry is empty")
        path = (campaign_dir / rel).resolve()
        # Path-traversal guard: an entry like ``../../etc/passwd`` would
        # escape the campaign_dir. The framework's mental model is that
        # frozen_configs live inside the rsynced experiment dir.
        try:
            path.relative_to(campaign_dir.resolve())
        except ValueError as exc:
            raise errors.SpecInvalid(
                f"frozen_configs entry {rel!r} resolves outside campaign_dir"
            ) from exc
        if not path.is_file():
            raise errors.SpecInvalid(f"frozen_configs entry {rel!r} is not a file: {path}")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
        key = _sha_kwarg_name(rel)
        if key in shas:
            raise errors.SpecInvalid(
                f"frozen_configs: kwarg name {key!r} collides (two configs with the same stem)"
            )
        shas[key] = digest
    return shas


def _sha_kwarg_name(rel: str) -> str:
    """Derive the tasks-kwarg name for a frozen config path."""
    stem = Path(rel).stem
    return f"{stem}_sha"


def _render_wrapper_body(
    *,
    run_name: str,
    argv: list[str],
    signature: Mapping[str, str],
) -> str:
    """Render the wrapper's ``@register_run`` function as Python source.

    The signature is the user-declared params (typed) plus ``**kwargs``
    so framework-injected identity fields (``<frozen>_sha``) and any
    future kwargs flow through without breaking the wrapper or
    ``validate-executor-signatures``.

    The body subprocess-invokes the argv. Every ``{param}`` placeholder
    is rewritten to ``str(param)`` so we never assume the kwarg type
    matches what subprocess wants (always a string).
    """
    params = ", ".join(f"{name}: {_TYPE_TO_PY[ty]}" for name, ty in signature.items())
    params_with_kwargs = (params + ", **kwargs") if params else "**kwargs"

    rendered_argv = ", ".join(_render_argv_token(token, signature) for token in argv)

    return (
        f"@register_run\n"
        f"def {run_name}({params_with_kwargs}) -> None:\n"
        f'    """Auto-generated shell-command wrapper. See module docstring."""\n'
        f"    subprocess.check_call([{rendered_argv}])\n"
    )


_TYPE_TO_PY: dict[str, str] = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
}


def _render_argv_token(token: str, signature: Mapping[str, str]) -> str:
    """Render one argv token as a Python source expression.

    A bare token like ``"python3"`` renders as a string literal; a token
    like ``"{config}"`` renders as ``str(config)`` so subprocess gets
    string args regardless of the declared kwarg type. A mixed token
    like ``"--seed={seed}"`` is a single str-formatted expression.
    """
    import re

    placeholder_re = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")
    matches = list(placeholder_re.finditer(token))
    if not matches:
        return repr(token)
    if len(matches) == 1 and matches[0].group(0) == token:
        # Pure placeholder — emit ``str(name)`` for clean typing.
        return f"str({matches[0].group(1)})"
    # Mixed literal+placeholder — emit an f-string. Escape any preexisting
    # braces in the literal portion by doubling them.
    parts: list[str] = []
    cursor = 0
    for m in matches:
        literal = token[cursor : m.start()].replace("{", "{{").replace("}", "}}")
        parts.append(literal)
        parts.append("{" + m.group(1) + "}")
        cursor = m.end()
    parts.append(token[cursor:].replace("{", "{{").replace("}", "}}"))
    rendered = "".join(parts)
    return "f" + repr(rendered)
