"""Wrapper materializer for the interview's ``shell_command`` entry point.

A mature repo arriving with ``main.py`` (and optional frozen YAML
configs) declares its entry point as
``{kind: "shell_command", argv: [...], signature: {...}, frozen_configs: [...]}``
on ``interview.json``. This module materializes a thin Python wrapper at
``<campaign_dir>/.hpc/wrappers/<run_name>.py`` whose body
subprocess-invokes the argv with kwargs substituted in.

The wrapper exists to give the framework something to introspect:

* ``@register_run`` for ``discover_runs`` and the cluster runtime
* a typed function signature for ``validate-executor-signatures``
* a hashable identity (``run_signature_sha``) for drift detection

``main.py`` itself stays opaque and untouched.

``frozen_configs`` are hashed; the interview threads the resulting
``<basename>_sha`` fields into every materialized task's kwargs so
``cmd_sha`` distinguishes two different YAML files (and catches an
accidental in-place edit).

This module is framework-internal setup tooling: it lives in
``incorporation/`` because it materializes a runtime artifact, and the
artifact imports ``@register_run`` from :mod:`hpc_agent.experiment_kit`
— preserving the one-direction dependency ``incorporation/`` →
``experiment_kit/``.
"""

from __future__ import annotations

import hashlib
import shlex
from pathlib import Path
from typing import TYPE_CHECKING

from hpc_agent import errors

if TYPE_CHECKING:
    from collections.abc import Mapping
    from typing import Any


__all__ = [
    "materialize_shell_wrapper",
    "python_module_executor_cmd",
    "register_run_executor_cmd",
    "WrapperResult",
    "wrapper_executor_cmd",
]


_WRAPPERS_SUBDIR = Path(".hpc") / "wrappers"

# Auto-generated header — every materialized wrapper carries this docstring so
# operators reading the file know it's framework-managed.
_HEADER = '''"""Auto-generated by ``hpc-agent interview`` from intent.entry_point.

Do not edit by hand. The interview regenerates this file from the
declared argv + signature each time intent.entry_point changes. To
diverge from the wrapper pattern, drop ``entry_point`` from the next
intent.json and supply a hand-written ``@register_run`` notebook
instead.
"""
from __future__ import annotations

import subprocess
from hpc_agent.experiment_kit import register_run
'''

# Header for a solver-instrumented wrapper (entry_point.solver declared).
# The extra imports are the checkpoint-injection seam: the adapter renders
# the PETSC_OPTIONS fragments the wrapper exports around the subprocess.
_SOLVER_HEADER = '''"""Auto-generated by ``hpc-agent interview`` from intent.entry_point.

Do not edit by hand. The interview regenerates this file from the
declared argv + signature each time intent.entry_point changes. To
diverge from the wrapper pattern, drop ``entry_point`` from the next
intent.json and supply a hand-written ``@register_run`` notebook
instead.

PETSc checkpoint-instrumented (intent.entry_point.solver): the wrapper
exports a ``PETSC_OPTIONS`` fragment that makes the solver dump its
solution each step into the stable per-task checkpoint dir, caps the
solve at 2 steps under the checkpoint-canary probe, and — when the app
declared a restart flag — rotates the previous attempt's dump into the
restart slot and appends the flag to argv. The entry point itself
stays opaque and untouched.
"""
from __future__ import annotations

import os
import subprocess
from hpc_agent.experiment_kit import register_run
from hpc_agent.experiment_kit.solver_adapters import petsc as _petsc
'''

# The solver kinds the wrapper materializer can instrument. One adapter today;
# the wire field is a discriminated hint so the vocabulary can grow.
_SOLVER_OBJECTS: tuple[str, ...] = ("ts", "snes")


class WrapperResult:
    """Outcome of materializing a shell_command wrapper.

    Light value type, not a Pydantic model, because it's an
    internal interview-primitive return — not a wire surface.
    """

    __slots__ = ("wrapper_path", "frozen_shas")

    def __init__(self, wrapper_path: Path, frozen_shas: Mapping[str, str]) -> None:
        self.wrapper_path = wrapper_path
        # dict copy so the caller cannot mutate our internal state.
        self.frozen_shas: dict[str, str] = dict(frozen_shas)


def materialize_shell_wrapper(
    *,
    campaign_dir: Path,
    run_name: str,
    argv: list[str],
    signature: Mapping[str, str],
    frozen_configs: list[str],
    solver: Mapping[str, Any] | None = None,
) -> WrapperResult:
    """Write ``<campaign_dir>/.hpc/wrappers/<run_name>.py`` and hash frozen configs.

    Pure: same inputs produce the same file bytes (modulo no timestamps
    embedded). Idempotent: re-running with the same inputs overwrites
    byte-equivalently. The caller (``record_interview``) controls atomic
    semantics by deciding when to invoke this.

    Returns a :class:`WrapperResult` carrying the wrapper path and a
    ``{basename_sha: hex_digest}`` mapping the interview threads into
    tasks-kwargs for identity (``cmd_sha`` inclusion).

    Raises :class:`errors.SpecInvalid` when a frozen config path is
    missing or escapes the campaign_dir, or when *solver* is malformed;
    the interview surfaces this as spec_invalid at the wire boundary.

    *solver* (optional) requests a checkpoint-instrumented wrapper for a
    known solver library: ``{"kind": "petsc", "solver_object": "ts"|"snes",
    "resume_flag": "--restart-file"|None}``. See :data:`_SOLVER_HEADER`.
    """
    # Validate the solver hint + hash frozen configs first — if either is
    # invalid, fail before touching the filesystem so a bad spec leaves no
    # residue (no empty wrappers/ dir, no half-written wrapper file pointing
    # at a missing config). Atomicity matters here because the caller
    # surfaces the error via the spec_invalid envelope.
    solver_parts = _validate_solver(solver)
    frozen_shas = _hash_frozen_configs(campaign_dir, frozen_configs)

    wrappers_dir = campaign_dir / _WRAPPERS_SUBDIR
    wrappers_dir.mkdir(parents=True, exist_ok=True)

    if solver_parts is not None:
        solver_object, resume_flag = solver_parts
        body = _render_solver_wrapper_body(
            run_name=run_name,
            argv=argv,
            signature=signature,
            solver_object=solver_object,
            resume_flag=resume_flag,
        )
        header = _SOLVER_HEADER
    else:
        body = _render_wrapper_body(run_name=run_name, argv=argv, signature=signature)
        header = _HEADER
    wrapper_path = wrappers_dir / f"{run_name}.py"
    content = header + "\n" + body
    # Idempotency: skip the write when bytes are identical so an mtime-
    # sensitive consumer (or just a curious operator running `ls -la`)
    # doesn't see churn on a no-op re-run. The body has no timestamps,
    # so any byte difference here means the spec actually changed.
    if not wrapper_path.is_file() or wrapper_path.read_text(encoding="utf-8") != content:
        wrapper_path.write_text(content, encoding="utf-8")

    return WrapperResult(wrapper_path=wrapper_path, frozen_shas=frozen_shas)


def wrapper_executor_cmd(
    *,
    campaign_dir: Path,
    run_name: str,
) -> str:
    """Return the shell command to invoke ``<run_name>``'s wrapper on a task.

    The materialized wrapper is a Python module with ``@register_run``
    that injects a ``compute(args)`` callable into its namespace. The
    cluster-side dispatcher exports each kwarg from ``tasks.resolve(i)``
    as both ``HPC_KW_<NAME>`` and bare ``<NAME>`` env vars, then runs
    this shell command per task. The one-liner builds an ``args``
    namespace from those env vars and dispatches.

    Returned form is a shell command suitable for stamping into the
    submit-flow spec / sidecar's ``executor`` field; ``submit-flow``
    consumes it as-is.

    Note: assumes the wrapper has already been materialized at
    ``<campaign_dir>/.hpc/wrappers/<run_name>.py``. The helper just
    composes the command — it neither writes nor verifies the wrapper.
    """
    rel = (_WRAPPERS_SUBDIR / f"{run_name}.py").as_posix()
    # Deterministic dispatch via the deployed ``executor_cli`` entry (#351) —
    # ``run-registered`` imports the module by path (no package install needed
    # on the cluster), builds args from the HPC_KW_* contract, and calls the
    # decorator-injected compute(args). This replaces the old nested
    # ``python3 -c "<single-quoted program>"`` form, whose quoting broke when
    # re-escaped through the worker's shell. No ``--run-name`` here: the
    # wrapper's internal registration name is an implementation detail of the
    # materializer, so we dispatch the module's single injected compute.
    #
    # rel is POSIX: this runs on the Linux cluster even when the campaign was
    # authored on Windows (a backslash path would break $REPO_DIR resolution).
    #
    # --no-default-output: a shell wrapper subprocess-invokes the user's argv,
    # which writes its own output — the framework must NOT inject an
    # output_file (the old one-liner didn't). The direct @register_run case
    # DOES default it (a bare `return dict` needs somewhere to land).
    return (
        f"python3 -m hpc_agent.executor_cli run-registered {shlex.quote(rel)} --no-default-output"
    )


def register_run_executor_cmd(
    *,
    campaign_dir: Path,
    run_path: Path,
    run_name: str | None = None,
) -> str:
    """Return the shell command to invoke a ``@register_run``-decorated
    function in the user's existing file on a task.

    Mirror of :func:`wrapper_executor_cmd` for the **direct-decoration**
    case — where the user's existing executor file carries
    ``@register_run`` (as opposed to a materialized wrapper at
    ``.hpc/wrappers/<run_name>.py`` for the shell_command fallback).

    The ``@register_run`` decorator injects ``compute(args)`` into the
    module's namespace at decoration time. The one-liner imports the
    user's file by path, builds an ``args`` Namespace from ``HPC_KW_*``
    env vars exported by the cluster dispatcher, and calls
    ``compute(args)`` — which the decorator's wrapper then routes
    through the user's function and writes the dict result to
    ``args.output_file`` if one was provided.

    Without this helper, the framework would naively use
    ``python3 <run_path>`` as the executor command; the dispatcher
    passes kwargs only as env vars (never argv), so a file whose
    ``__main__`` block uses argparse would fail with "required argument
    missing" — and a file without a ``__main__`` block would silently
    exit 0 without invoking ``compute``. Both empirical cases observed
    in live demos.

    *run_path* must be a path inside *campaign_dir*; the embedded
    POSIX relative form ships with the campaign rsync and is resolved
    against ``$REPO_DIR`` at task time, matching the wrapper case.

    *run_name*, when given (the decorated function's name), is forwarded
    as ``--run-name`` so the dispatcher validates the run against the
    module's ``_RUNS`` registry — a stale executor_cmd then fails loudly,
    naming the mismatch, instead of silently running the wrong module.
    """
    rel = run_path.relative_to(campaign_dir).as_posix()
    # Deterministic dispatch via the deployed ``executor_cli`` entry (#351):
    # ``run-registered`` imports the user's file by path, builds args from the
    # HPC_KW_* contract, and calls the decorator-injected compute(args). It
    # defaults ``output_file`` to ``$RESULT_DIR/metrics.json`` so a function
    # that just ``return``s a dict lands its result on disk — without it the
    # dispatcher exports ``RESULT_DIR`` but no ``HPC_KW_OUTPUT_FILE`` (the
    # HPC_KW_* contract carries only ``tasks.resolve(i)`` kwargs, never
    # framework metadata), so the dict was silently dropped (0.10.3 demo:
    # 100 tasks ran, only ``_runtime.json`` written). An explicit
    # ``HPC_KW_OUTPUT_FILE`` (from declared FLAGS) still wins.
    #
    # This replaces the old nested ``python3 -c "<single-quoted program>"``,
    # whose quoting broke when re-escaped through the worker's shell — the
    # recurring "agent hand-edits a divined executor_cmd" failure (#351).
    parts = ["python3", "-m", "hpc_agent.executor_cli", "run-registered", shlex.quote(rel)]
    if run_name is not None:
        parts += ["--run-name", shlex.quote(run_name)]
    return " ".join(parts)


def python_module_executor_cmd(*, module: str, function: str = "main") -> str:
    """Return the shell command to dispatch a ``python_module`` entry point.

    The python_module entry point names an importable ``<module>:<function>``
    (e.g. ``my_pkg.train:main``) — a plain, *undecorated* function the framework
    introspects. Like :func:`register_run_executor_cmd`, the per-task command
    routes through the deployed ``executor_cli`` so the cluster dispatcher's
    ``HPC_KW_*`` contract reaches the function with coerced kwargs:
    ``run-module`` imports the module by name (under ``$REPO_DIR`` on
    ``PYTHONPATH``) and applies the same ``compute`` wrapper ``@register_run``
    would inject.

    Without this helper the materialized entry_point carried NO ``executor_cmd``
    (the interview recorded ``{module, function}`` for introspection only), so a
    python_module submission had no runnable per-task command — and a bare
    ``module:function`` stamped into the sidecar gets exec'd as a shell command
    and exits 127 (the ridge_imp class). ``output_file`` defaults to
    ``$RESULT_DIR/metrics.json`` (handled inside ``run-module``), so a function
    that just ``return``s a dict still lands its result on disk.

    Unlike the wrapper / direct-decoration cases, the dispatch target is a
    dotted *module name*, not a campaign-relative file path — nothing is
    materialized and there is no path to make POSIX.
    """
    spec = f"{module}:{function}"
    return f"python3 -m hpc_agent.executor_cli run-module {shlex.quote(spec)}"


def _validate_solver(solver: Mapping[str, Any] | None) -> tuple[str, str | None] | None:
    """Normalize the optional solver hint to ``(solver_object, resume_flag)``.

    The wire schema (``_PetscSolverHint``) already constrains the shape, but
    this layer takes plain dicts (the ops boundary), so it re-validates —
    a malformed hint must fail before any file is written, with the same
    :class:`errors.SpecInvalid` the frozen-config guards use.
    """
    if solver is None:
        return None
    kind = solver.get("kind")
    if kind != "petsc":
        raise errors.SpecInvalid(
            f"entry_point.solver.kind {kind!r} is not a known solver adapter (expected 'petsc')"
        )
    solver_object = solver.get("solver_object", "ts")
    if solver_object not in _SOLVER_OBJECTS:
        raise errors.SpecInvalid(
            f"entry_point.solver.solver_object {solver_object!r} invalid "
            f"(expected one of {list(_SOLVER_OBJECTS)})"
        )
    resume_flag = solver.get("resume_flag")
    if resume_flag is not None:
        # Same flag shape the adapter's resume_args enforces at run time;
        # checking here keeps a bad flag a spec_invalid, not a task crash.
        from hpc_agent.experiment_kit.solver_adapters.petsc import resume_args

        try:
            resume_args(resume_flag, "probe")
        except ValueError as exc:
            raise errors.SpecInvalid(f"entry_point.solver.resume_flag: {exc}") from exc
    return solver_object, resume_flag


def _hash_frozen_configs(campaign_dir: Path, frozen_configs: list[str]) -> dict[str, str]:
    """Resolve each path against *campaign_dir*, hash its bytes, derive a kwarg name.

    The kwarg name is ``<filename_stem>_sha`` — e.g. ``configs/exp_42.yaml``
    becomes ``exp_42_sha``. Collisions (two configs with the same stem)
    are rejected: the interview can't thread two different shas under
    the same kwarg.
    """
    shas: dict[str, str] = {}
    for rel in frozen_configs:
        if not rel:
            raise errors.SpecInvalid("frozen_configs entry is empty")
        path = (campaign_dir / rel).resolve()
        # Path-traversal guard: an entry like ``../../etc/passwd`` would
        # escape the campaign_dir. The framework's mental model is that
        # frozen_configs live inside the rsynced experiment dir.
        try:
            path.relative_to(campaign_dir.resolve())
        except ValueError as exc:
            raise errors.SpecInvalid(
                f"frozen_configs entry {rel!r} resolves outside campaign_dir"
            ) from exc
        if not path.is_file():
            raise errors.SpecInvalid(f"frozen_configs entry {rel!r} is not a file: {path}")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
        key = _sha_kwarg_name(rel)
        if key in shas:
            raise errors.SpecInvalid(
                f"frozen_configs: kwarg name {key!r} collides (two configs with the same stem)"
            )
        shas[key] = digest
    return shas


def _sha_kwarg_name(rel: str) -> str:
    """Derive the tasks-kwarg name for a frozen config path."""
    stem = Path(rel).stem
    return f"{stem}_sha"


def _render_wrapper_body(
    *,
    run_name: str,
    argv: list[str],
    signature: Mapping[str, str],
) -> str:
    """Render the wrapper's ``@register_run`` function as Python source.

    The signature is the user-declared params (typed) plus ``**kwargs``
    so framework-injected identity fields (``<frozen>_sha``) and any
    future kwargs flow through without breaking the wrapper or
    ``validate-executor-signatures``.

    The body subprocess-invokes the argv. Every ``{param}`` placeholder
    is rewritten to ``str(param)`` so we never assume the kwarg type
    matches what subprocess wants (always a string).
    """
    params = ", ".join(f"{name}: {_TYPE_TO_PY[ty]}" for name, ty in signature.items())
    params_with_kwargs = (params + ", **kwargs") if params else "**kwargs"

    rendered_argv = ", ".join(_render_argv_token(token, signature) for token in argv)

    return (
        f"@register_run\n"
        f"def {run_name}({params_with_kwargs}) -> None:\n"
        f'    """Auto-generated shell-command wrapper. See module docstring."""\n'
        f"    subprocess.check_call([{rendered_argv}])\n"
    )


def _render_solver_wrapper_body(
    *,
    run_name: str,
    argv: list[str],
    signature: Mapping[str, str],
    solver_object: str,
    resume_flag: str | None,
) -> str:
    """Render the PETSc checkpoint-instrumented wrapper function.

    Same signature/argv rendering as :func:`_render_wrapper_body`; the body
    differs in three framework-owned steps around the subprocess call:

    1. extend ``PETSC_OPTIONS`` with the adapter's per-step solution dump
       (into the stable per-task checkpoint dir) — and, under the
       checkpoint-canary probe, the 2-step solve cap;
    2. when the app declared *resume_flag*, rotate the previous attempt's
       dump into the restart slot and append the flag to argv;
    3. launch the argv with the extended environment.

    Step 2 must precede step 3: the dump option truncates the solution file
    when the solver starts, so the restart state has to be moved out of its
    way first (see :func:`solver_adapters.petsc.promote_restart`).
    """
    params = ", ".join(f"{name}: {_TYPE_TO_PY[ty]}" for name, ty in signature.items())
    params_with_kwargs = (params + ", **kwargs") if params else "**kwargs"

    rendered_argv = ", ".join(_render_argv_token(token, signature) for token in argv)

    resume_lines = ""
    if resume_flag is not None:
        resume_lines = (
            "    _restart = _petsc.promote_restart()\n"
            "    if _restart is not None:\n"
            f"        argv += _petsc.resume_args({resume_flag!r}, _restart)\n"
        )

    return (
        f"@register_run\n"
        f"def {run_name}({params_with_kwargs}) -> None:\n"
        f'    """Auto-generated PETSc-instrumented wrapper. See module docstring."""\n'
        f"    argv = [{rendered_argv}]\n"
        f"    opts = []\n"
        f'    if os.environ.get("PETSC_OPTIONS"):\n'
        f'        opts.append(os.environ["PETSC_OPTIONS"])\n'
        f"    opts.append(_petsc.checkpoint_options(\n"
        f"        solver_kind={solver_object!r}, solution_path=_petsc.wrapper_solution_path()\n"
        f"    ))\n"
        f'    if os.environ.get("HPC_CHECKPOINT_CANARY", "").strip() == "1":\n'
        f"        opts.append(_petsc.canary_options({solver_object!r}))\n"
        f"{resume_lines}"
        f"    env = dict(os.environ)\n"
        f'    env["PETSC_OPTIONS"] = " ".join(opts)\n'
        f"    subprocess.check_call(argv, env=env)\n"
    )


_TYPE_TO_PY: dict[str, str] = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
}


def _render_argv_token(token: str, signature: Mapping[str, str]) -> str:
    """Render one argv token as a Python source expression.

    A bare token like ``"python3"`` renders as a string literal; a token
    like ``"{config}"`` renders as ``str(config)`` so subprocess gets
    string args regardless of the declared kwarg type. A mixed token
    like ``"--seed={seed}"`` is a single str-formatted expression.
    """
    import re

    placeholder_re = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")
    matches = list(placeholder_re.finditer(token))
    if not matches:
        return repr(token)
    if len(matches) == 1 and matches[0].group(0) == token:
        # Pure placeholder — emit ``str(name)`` for clean typing.
        return f"str({matches[0].group(1)})"
    # Mixed literal+placeholder — emit an f-string. Escape any preexisting
    # braces in the literal portion by doubling them.
    parts: list[str] = []
    cursor = 0
    for m in matches:
        literal = token[cursor : m.start()].replace("{", "{{").replace("}", "}}")
        parts.append(literal)
        parts.append("{" + m.group(1) + "}")
        cursor = m.end()
    parts.append(token[cursor:].replace("{", "{{").replace("}", "}}"))
    rendered = "".join(parts)
    return "f" + repr(rendered)
