hoffman2:
  host: hoffman2.idre.ucla.edu
  user: jamesdc1
  scheduler: sge
  scratch: /u/scratch/j/jamesdc1
  modules: [python/3.11.9]
  conda_source: /u/local/apps/anaconda3/2024.06/etc/profile.d/conda.sh
  conda_envs: [harxhar-dl]
  gpu_types: [a100, h200, a6000, h100, v100, rtx2080ti]
  constraints:
    max_array_size: 100
    max_walltime: "2:00:00"
    max_concurrent_jobs: 2
    est_spin_up: "5m"

discovery:
  host: discovery2.usc.edu
  user: jc_905
  scheduler: slurm
  account: pollok_1603
  scratch: /scratch1/jc_905
  modules: []
  conda_source: /apps/conda/miniforge3/25.3.0/etc/profile.d/conda.sh
  conda_envs: [project-cucuringu]
  gpu_types: [a100, a40, v100, l40s]
  gpu_constraint: "a100|a40|v100|l40s"
  constraints:
    max_array_size: 100
    max_walltime: "2:00:00"
    max_concurrent_jobs: 2
    est_spin_up: "5m"
