"""Wire model for the ``validate-scaffold-staleness`` atom (#364).

A ``.hpc/`` scaffold generated by an *older* hpc-agent can survive an
upgrade and then fail on a compute node with a runtime ``ImportError`` —
because nothing at submit time checked that the generated scaffold's
``hpc_agent.*`` imports still resolve against the *installed* package.
This validator is the cheap, local (no-SSH) pre-submit gate that catches
that class before the expensive cluster round-trip, the same theme as
``dry-run-local`` (#205): validate the broken-code case locally rather
than discover it deep in a cluster task.

The atom takes no ``--spec`` — the only input it needs is the experiment
directory the dispatcher already threads in — so it carries an output
model only.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from hpc_agent._wire.workflows.validate_campaign import (
    ValidatorFinding,  # noqa: TC001 — Pydantic resolves the annotation at runtime
)


class ValidateScaffoldStalenessResult(BaseModel):
    """Output — the standard ``findings`` envelope plus stamp diagnostics.

    Empty ``findings`` == pass. A ``stale_scaffold`` finding (severity
    ``error``) blocks submission. ``status`` / ``installed_version`` /
    ``stamp_version`` carry the diagnosis even when there is no finding, so
    a caller can tell "fresh because the stamp matched" from "fresh because
    every import resolved."
    """

    model_config = ConfigDict(extra="forbid")

    findings: list[ValidatorFinding] = Field(default_factory=list)
    status: Literal["fresh", "stale"] = Field(
        default="fresh",
        description="'fresh' when the scaffold is compatible; 'stale' when it must be regenerated.",
    )
    installed_version: str = Field(
        description="The installed hpc_agent.__version__ the scaffold was checked against."
    )
    stamp_version: str | None = Field(
        default=None,
        description=(
            "The generator version stamped in .hpc/.scaffold_meta.json, or null "
            "for an unstamped (legacy) scaffold."
        ),
    )
