"""``build-tasks-py`` primitive — scaffold the per-experiment ``.hpc/tasks.py``.

Given a cartesian-product axes spec + per-executor flag declarations,
emit a ``tasks.py`` that follows the canonical contract (FLAGS / total()
/ resolve()). Replaces the slash-command prose that walked the agent
through writing the file by hand.

Defaults to Pattern 1 (cartesian product) from ``tasks_example.py`` —
the 80% case for grid sweeps. For Pattern 2 (chunking) / Pattern 3
(date windows), the user hand-edits the generated file; this primitive
just gets the agent to a known-good starting point instead of
re-deriving the framework contract from prose.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from claude_hpc import errors
from claude_hpc._internal._primitive import SideEffect, primitive
from claude_hpc._schema_models.build_tasks_py import BuildTasksPyInput

if TYPE_CHECKING:
    from pathlib import Path


# Whitelist of types we know how to emit. Anything else (numpy.float32,
# user-defined classes, Decimal) routes to ``str`` since cluster-side
# argparse downcasts via the type ctor anyway and emitting opaque types
# would break the generated file.
_FLAG_TYPE_NAMES: dict[type, str] = {
    int: "int",
    float: "float",
    str: "str",
    bool: "bool",
}


def _flag_type_repr(tp: Any) -> str:
    """Return a Python source token for the given flag type.

    Strings in *tp* (e.g. ``"int"``) pass through unchanged so callers
    can spell types without importing them. Class objects map via
    :data:`_FLAG_TYPE_NAMES`.
    """
    if isinstance(tp, str):
        return tp
    return _FLAG_TYPE_NAMES.get(tp, "str")


def _render_flag(flag: dict[str, Any]) -> str:
    """Render one flag dict as a ``flag(...)`` source expression.

    Required keys: ``name``, ``type``. Optional: ``default``.
    """
    name = flag["name"]
    type_token = _flag_type_repr(flag["type"])
    if "default" in flag:
        return f"flag({name!r}, {type_token}, default={flag['default']!r})"
    return f"flag({name!r}, {type_token})"


def _render_flags_block(flags_by_executor: dict[str, list[dict[str, Any]]]) -> str:
    """Render the FLAGS dict assignment as multi-line Python source."""
    lines = ["FLAGS: dict[str, list] = {"]
    for module_path, flag_list in flags_by_executor.items():
        lines.append(f"    {module_path!r}: [")
        lines.append("        *generic_args(),")
        for f in flag_list:
            lines.append(f"        {_render_flag(f)},")
        lines.append("    ],")
    lines.append("}")
    return "\n".join(lines)


def _render_tasks_block(axes: list[dict[str, Any]]) -> str:
    """Render the cartesian-product _TASKS list comprehension.

    *axes* is ``[{"name": ..., "values": [...]}, ...]``. We emit a list
    comprehension that mirrors the canonical Pattern 1 from
    ``tasks_example.py``. Single-axis sweeps render as a simple list
    comprehension; multi-axis as ``itertools.product``.
    """
    if len(axes) == 1:
        ax = axes[0]
        return (
            f"_TASKS: list[dict] = [\n    {{{ax['name']!r}: v}}\n    for v in {ax['values']!r}\n]"
        )
    names = [ax["name"] for ax in axes]
    values = [ax["values"] for ax in axes]
    var_tuple = ", ".join(names)
    dict_body = ", ".join(f"{n!r}: {n}" for n in names)
    args = ", ".join(repr(v) for v in values)
    return (
        f"_TASKS: list[dict] = [\n"
        f"    {{{dict_body}}}\n"
        f"    for {var_tuple} in itertools.product({args})\n"
        f"]"
    )


_TEMPLATE = '''"""Per-experiment task list — cartesian product over the configured axes.

Generated by ``hpc-mapreduce build-tasks-py``. Pattern 1 (cartesian
product) from ``claude_hpc/templates/tasks_example.py``. Hand-edit
to switch to Pattern 2 (chunking) or Pattern 3 (date windows) — the
contract is just FLAGS / total() / resolve().
"""

from __future__ import annotations

import itertools  # noqa: F401 — used by the multi-axis _TASKS render

from claude_hpc.executor_cli import flag, generic_args  # noqa: F401

{flags_block}

{tasks_block}


def total() -> int:
    return len(_TASKS)


def resolve(task_id: int) -> dict:
    return _TASKS[task_id]
'''


@primitive(
    name="build-tasks-py",
    verb="scaffold",
    side_effects=[
        SideEffect("writes-sidecar", "<experiment>/.hpc/tasks.py"),
    ],
    error_codes=[errors.SpecInvalid],
    idempotent=True,
    idempotency_key="experiment_dir",
    cli="hpc-mapreduce build-tasks-py --spec <path>",
    agent_facing=True,
)
def build_tasks_py(
    experiment_dir: Path,
    *,
    spec: BuildTasksPyInput,
) -> dict[str, Any]:
    """Scaffold ``<experiment>/.hpc/tasks.py`` from the supplied axes + flags.

    The wire-validated ``spec`` carries ``axes``, ``flags_by_executor``,
    and ``force``; ``experiment_dir`` is the framework-context kwarg
    (the spec's wire surface intentionally doesn't hold it).

    Parameters
    ----------
    experiment_dir:
        Repo root. The output goes to ``<experiment>/.hpc/tasks.py``.
    axes:
        Ordered list of ``{"name": str, "values": list}``. Order
        defines the cartesian-product convention used by
        :func:`compute_wave_map`. Single-axis sweeps render as a
        plain list comprehension; multi-axis use ``itertools.product``.
    flags_by_executor:
        Map from importable executor module path (e.g.
        ``"src.ml_ridge"``) to a list of flag dicts. Each flag is
        ``{"name": str, "type": int|float|str|bool|"<token>",
        "default"?: Any}``. The dispatcher errors fast on a missing
        executor entry, so include every executor in the repo that
        ``/submit-hpc`` might pick at submit time.
    force:
        Overwrite an existing ``.hpc/tasks.py``. Default is
        refuse-without-force — same semantics as ``axes-init``,
        because the user may have hand-edited the generated file
        (Pattern 2 / Pattern 3 conversions).

    Returns
    -------
    ``{path, wrote, reason, n_tasks}``. ``n_tasks`` is the
    cartesian-product cardinality the rendered file will report
    via ``total()``.
    """
    axes = [a.model_dump() for a in spec.axes]
    # exclude_none on the flag dump so a flag without ``default`` doesn't
    # acquire a synthetic ``default: None`` (the renderer's ``"default"
    # in flag`` check would then emit a spurious ``default=None`` arg).
    flags_by_executor = {
        k: [f.model_dump(exclude_none=True) for f in v] for k, v in spec.flags_by_executor.items()
    }
    force = bool(spec.force)

    target = experiment_dir / ".hpc" / "tasks.py"
    if target.exists() and not force:
        return {
            "path": str(target),
            "wrote": False,
            "reason": (
                f"{target} already exists; pass force=true to overwrite. "
                "(Refuse-without-force preserves any hand-edits — e.g. a "
                "Pattern 2/3 conversion.)"
            ),
            "n_tasks": 0,
        }

    flags_block = _render_flags_block(flags_by_executor)
    tasks_block = _render_tasks_block(axes)
    source = _TEMPLATE.format(flags_block=flags_block, tasks_block=tasks_block)

    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(source, encoding="utf-8")
    tmp.replace(target)

    n_tasks = 1
    for ax in axes:
        n_tasks *= len(ax["values"])

    return {
        "path": str(target),
        "wrote": True,
        "reason": f"wrote {target} ({n_tasks} tasks)",
        "n_tasks": n_tasks,
    }
