"""Executor-side CLI helpers — the building blocks for ``.hpc/`` glue.

Static framework module. Provides:

- :class:`Flag` and the :func:`flag` constructor — declarative spec for one
  argparse argument.
- :func:`generic_args` and :func:`gpu_args` — pre-built flag lists every
  executor and every GPU executor commonly needs.
- :func:`build_parser_from_flags` — turns a flag list into an
  :class:`argparse.ArgumentParser`.

The auto-generated ``.hpc/tasks.py`` declares a per-executor FLAGS dict
keyed by importable module path:

.. code-block:: python

    # .hpc/tasks.py — auto-generated by /submit-hpc Step 6
    from hpc_agent.executor_cli import flag, generic_args, gpu_args

    FLAGS = {
        "src.ml_ridge":   [*generic_args(), flag("horizon", int, default=1)],
        "src.dl_patchts": [*generic_args(), *gpu_args(), flag("horizon", int)],
    }

    def resolve(task_id): ...
    def total(): ...

The matching ``.hpc/cli.py`` (also auto-generated, never hand-edited)
loads tasks.py, looks up the right FLAGS list per executor module, and
dispatches to ``compute(args)``:

.. code-block:: python

    # python -m cli src.ml_ridge --horizon 1 --output-file out.csv
    executor_module = sys.argv.pop(1)
    args = get_parser(executor_module).parse_args()
    importlib.import_module(executor_module).compute(args)

**The one cross-experiment convention:** every executor module exports
``compute(args) -> None``. The dispatcher hard-codes that name.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class Flag:
    """Declarative spec for one argparse flag.

    Names use Python identifier style (underscores). The CLI flag is
    produced as ``--{name.replace("_", "-")}``; argparse normalizes the
    parsed attribute back to ``args.{name}``.
    """

    name: str
    type: type | None = str
    default: Any = None
    required: bool = False
    choices: tuple[Any, ...] | None = None
    help: str = ""
    nargs: str | None = None
    action: str | None = None

    def add_to(self, parser: argparse.ArgumentParser) -> None:
        kwargs: dict[str, Any] = {"help": self.help}
        if self.required:
            kwargs["required"] = True
        if self.default is not None:
            kwargs["default"] = self.default
        elif not self.required and self.action is None:
            # Explicit None default for optional value-flags; lets executors
            # do `if args.foo is not None:` reliably. Skipped when an
            # ``action`` is set — a ``store_true`` flag must keep its
            # natural ``False`` default, not become ``None`` when absent.
            kwargs["default"] = None
        if self.choices is not None:
            kwargs["choices"] = list(self.choices)
        if self.nargs is not None:
            kwargs["nargs"] = self.nargs
        # ``action`` (e.g. ``store_true`` for boolean flags) is mutually
        # exclusive with ``type`` in argparse; when set it wins.
        if self.action is not None:
            kwargs["action"] = self.action
        elif self.type is not None:
            kwargs["type"] = self.type
        cli_flag = "--" + self.name.replace("_", "-")
        parser.add_argument(cli_flag, **kwargs)


def flag(
    name: str,
    type: type | None = str,
    *,
    default: Any = None,
    required: bool = False,
    choices: tuple[Any, ...] | list[Any] | None = None,
    help: str = "",
    nargs: str | None = None,
    action: str | None = None,
) -> Flag:
    """Concise constructor for a :class:`Flag` declaration."""
    return Flag(
        name=name,
        type=type,
        default=default,
        required=required,
        choices=tuple(choices) if choices is not None else None,
        help=help,
        nargs=nargs,
        action=action,
    )


def generic_args() -> list[Flag]:
    """Common flags every executor accepts.

    ``--output-file`` is the only contract requirement. The rest are
    common enough across experiment domains (windowing, RNG seed, data
    path) that defaulting to inclusion is more useful than not.
    Experiments that don't use ``--start``/``--end``/``--data-path``
    just ignore the parsed values.
    """
    return [
        flag(
            "output_file",
            str,
            required=True,
            help="Where to write executor results (per-task output path).",
        ),
        flag("seed", int, default=42, help="Random seed for deterministic reproduction."),
        flag(
            "start",
            int,
            default=0,
            help="Window start index/offset (interpretation is executor-specific).",
        ),
        flag(
            "end",
            int,
            default=-1,
            help="Window end index/offset (-1 = to end).",
        ),
        flag(
            "data_path",
            str,
            help="Path to input data (interpretation is executor-specific).",
        ),
    ]


def gpu_args() -> list[Flag]:
    """Common flags for GPU/DL executors.

    Add alongside :func:`generic_args` for any executor that runs on
    GPU. ``--epochs`` / ``--batch-size`` / ``--learning-rate`` default
    to None so each method can fall back to its own internal default
    while still being grid-overrideable from ``.hpc/tasks.py``.
    """
    return [
        flag("gpu_count", int, default=1, help="Number of GPUs to use."),
        flag("epochs", int, help="Training epochs (None = method-specific default)."),
        flag("batch_size", int, help="Training batch size (None = method-specific default)."),
        flag("learning_rate", float, help="Learning rate (None = method-specific default)."),
    ]


# Fields that uniquely define a Flag. Used to coerce a Flag-shaped object
# from a DIFFERENT module into THIS module's Flag — see _coerce_flag.
_FLAG_FIELDS = ("name", "type", "default", "required", "choices", "help", "nargs", "action")


def _coerce_flag(f: Any) -> Flag:
    """Normalize one FLAGS entry to a local :class:`Flag` instance.

    Accepts three shapes:

    * a local ``Flag`` — returned as-is;
    * a ``dict`` of Flag fields — splatted into ``Flag(**f)``;
    * any object exposing the full set of Flag fields — a structurally
      identical ``Flag`` defined in ANOTHER module (e.g. the inlined
      ``.hpc/cli.py`` copy that runs on a stdlib-only cluster node).
      ``isinstance`` is ``False`` across that class-identity gap, so a
      bare type check rejected a perfectly valid entry with ``TypeError``
      (#177). We rebuild a local ``Flag`` from its fields so the parser is
      always built with this module's ``add_to``.

    Anything else raises ``TypeError``.
    """
    if isinstance(f, Flag):
        return f
    if isinstance(f, dict):
        return Flag(**f)
    if all(hasattr(f, _attr) for _attr in _FLAG_FIELDS):
        return Flag(**{_attr: getattr(f, _attr) for _attr in _FLAG_FIELDS})
    raise TypeError(f"FLAGS entries must be Flag instances or dicts; got {type(f).__name__}")


def build_parser_from_flags(
    flags: list[Flag] | list[dict[str, Any]],
    *,
    description: str = "",
) -> argparse.ArgumentParser:
    """Build an :class:`argparse.ArgumentParser` from a declarative flag list.

    Each entry may be a :class:`Flag` instance, a dict with the same keys,
    or a structurally-identical ``Flag`` from another module (see
    :func:`_coerce_flag`). The returned parser is ready to
    ``.parse_args(argv)``.
    """
    parser = argparse.ArgumentParser(description=description)
    for f in flags:
        _coerce_flag(f).add_to(parser)
    return parser


# --------------------------------------------------------------------------- #
# run-registered: the deterministic @register_run dispatcher (#351)
# --------------------------------------------------------------------------- #
#
# Replaces the brittle ``python3 -c "<nested one-liner>"`` the framework used to
# stamp into the run sidecar's ``executor`` field for a @register_run entry
# point. That form nested a single-quoted Python program inside a double-quoted
# ``-c`` argument; re-escaped through the worker's shell it broke, and the agent
# would hand-edit a divined replacement (the recurring failure class, demo
# 2026-06-24). This is the *same* work — import the module by path, build a
# Namespace from ``HPC_KW_*``, call the decorator-injected ``compute(args)`` —
# but as a real argv entry with no nested quoting, defined and tested once.
#
# Lives here (not in the full ``hpc_agent.cli``) because ``executor_cli`` is the
# stdlib-only module deployed to the cluster (``transport._build_deploy_items``),
# so the dispatch resolves under any cluster python without paying the full-CLI
# import/argparse cost per array task.


def _load_registered_module(module_rel: str) -> Any:
    """Import the campaign-relative module file at ``$REPO_DIR/<module_rel>``.

    Loaded by path (not package name): a ``@register_run`` file or a
    materialized wrapper lives at an arbitrary campaign-relative location, not
    necessarily an importable package. ``REPO_DIR`` is exported by the
    cluster-side dispatcher (``hpc_preamble.sh``); it defaults to ``.`` so the
    entry runs locally under test. Importing the module runs its
    ``@register_run`` decorator, which injects ``compute`` into its namespace.
    """
    import importlib.util
    import os

    repo_dir = os.environ.get("REPO_DIR", ".")
    path = os.path.join(repo_dir, module_rel)
    if not os.path.isfile(path):
        raise SystemExit(
            f"[run-registered] cannot import a module from {path!r}: no such file "
            "(is REPO_DIR set and the campaign deployed?)"
        )
    spec = importlib.util.spec_from_file_location("_hpc_registered", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"[run-registered] cannot import a module from {path!r}")
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        # User code import-time failure (syntax error, a failed
        # `from hpc_agent import register_run`, …). Surface the cause as a
        # clean dispatch error instead of a raw cluster-side traceback.
        raise SystemExit(f"[run-registered] failed importing {path!r}: {exc}") from exc
    return module


def _registered_kwargs() -> dict[str, str]:
    """Collect ``HPC_KW_*`` task kwargs — the dispatcher's stable contract.

    Each ``HPC_KW_<NAME>=<value>`` export becomes ``<name>=<value>`` (prefix
    stripped, lowercased). Values are strings; the ``@register_run`` ``compute``
    wrapper coerces each to its parameter's annotated type before the call
    (``experiment_kit._runtime._make_compute``, #350/#351).
    """
    import os

    prefix = "HPC_KW_"
    return {
        key[len(prefix) :].lower(): value
        for key, value in os.environ.items()
        if key.startswith(prefix)
    }


def run_registered(argv: list[str] | None = None) -> int:
    """Dispatch one task to a ``@register_run`` executor (#351).

    ``python3 -m hpc_agent.executor_cli run-registered <module_rel>
    [--run-name NAME]``. ``compute`` is the single callable ``@register_run``
    injects per module (one run per module is the expected shape).
    ``--run-name``, when supplied, is validated against the module's ``_RUNS``
    registry so a stale spec fails loudly *here* — naming the mismatch — rather
    than silently running the wrong module.

    ``output_file`` defaults to ``$RESULT_DIR/metrics.json`` so a function that
    just ``return``s a dict lands its result on disk; an explicit
    ``HPC_KW_OUTPUT_FILE`` (from declared FLAGS) still wins via ``setdefault``.
    """
    import argparse
    import os

    parser = argparse.ArgumentParser(
        prog="hpc_agent.executor_cli run-registered",
        description="Dispatch one task to a @register_run executor (#351).",
    )
    parser.add_argument(
        "module_rel",
        help="Campaign-relative path to the @register_run / wrapper module "
        "(resolved against $REPO_DIR on the cluster).",
    )
    parser.add_argument(
        "--run-name",
        default=None,
        help="Registered run name; validated against the module's _RUNS registry when supplied.",
    )
    parser.add_argument(
        "--no-default-output",
        action="store_true",
        help="Do not default output_file to $RESULT_DIR/metrics.json.",
    )
    args = parser.parse_args(argv)

    module = _load_registered_module(args.module_rel)

    runs = getattr(module, "_RUNS", None)
    if args.run_name is not None and isinstance(runs, dict) and args.run_name not in runs:
        raise SystemExit(
            f"[run-registered] no @register_run named {args.run_name!r} in "
            f"{args.module_rel!r}; found {sorted(runs)}. The spec is stale — "
            "re-run the interview so the executor_cmd matches the module."
        )

    compute = getattr(module, "compute", None)
    if compute is None:
        raise SystemExit(
            f"[run-registered] module {args.module_rel!r} exports no compute(); "
            "is the entry point @register_run-decorated?"
        )

    kwargs = _registered_kwargs()
    if not args.no_default_output:
        kwargs.setdefault(
            "output_file",
            os.path.join(os.environ.get("RESULT_DIR", "."), "metrics.json"),
        )
    compute(argparse.Namespace(**kwargs))
    return 0


_SUBCOMMANDS = {"run-registered": run_registered}


def main(argv: list[str] | None = None) -> int:
    """``python -m hpc_agent.executor_cli <subcommand> ...`` entry point.

    Only ``run-registered`` exists today (the deterministic ``@register_run``
    dispatcher, #351). The declarative helper API above (``flag`` /
    ``generic_args`` / ``build_parser_from_flags``) is import-only and
    unaffected — importing this module never runs ``main``.
    """
    import sys

    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] not in _SUBCOMMANDS:
        choices = ", ".join(sorted(_SUBCOMMANDS))
        sys.stderr.write(f"usage: python -m hpc_agent.executor_cli {{{choices}}} ...\n")
        return 2
    return _SUBCOMMANDS[argv[0]](argv[1:])


if __name__ == "__main__":
    raise SystemExit(main())
