"""Unit E (#362) — async-refill is byte-identical to the sync ladder when off.

Two properties this pins:

1. **Flag-off byte-identity.** With ``async_refill`` unset/false,
   ``campaign_advance`` (:mod:`hpc_agent.meta.campaign.atoms.advance`) resolves
   the synchronous rule ladder ``[_over_budget, _wait_in_flight,
   _circuit_breaker, _resubmit_cap, _converged]`` (``advance.py::campaign_advance``
   ``rules``). We drive a full cartesian grid of synthetic evidence
   (``in_flight`` 0..N × budget exhausted/not × ack fresh/stale × breaker
   tripped/not × converged/not) and assert every decision equals an independent
   reference implementation of that precedence — and that the async-only
   ``refill`` outcome is UNREACHABLE flag-off (``decision != "refill"`` and
   ``refill_count is None`` for every grid point).

2. **The async branch is gated, not dead.** The same steady-state evidence that
   the sync ladder answers ``wait_in_flight`` for is answered ``refill`` once the
   flag is on — demonstrating the async ``_refill`` rule (``advance.py::_refill``)
   exists yet is reachable ONLY behind the opt-in.

The grid over five INDEPENDENT evidence dimensions is generated by patching the
evidence atoms (status/budget/converged/breaker/resubmit/ack) — the same
``synthetic evidence`` seam ``tests/.../atoms/test_advance_refill.py`` uses,
because holding those five dimensions independent with real journal records is
not feasible (a terminal-failed run also moves budget-spend and the iteration
count). Real-journal ANCHOR tests below ground the reference against actual
on-disk state at representative points, per the "no mocks where feasible" rule.

The livelock guard (``load_context._async_should_refill`` routes refill ONLY when
advance decides refill; a full pool routes to drain) is pinned at the bottom with
real journals + a real manifest.
"""

from __future__ import annotations

import itertools
from typing import TYPE_CHECKING, Any

import pytest

from hpc_agent.meta.campaign.atoms.advance import campaign_advance

if TYPE_CHECKING:
    from pathlib import Path

_CID = "tune_async"
_BREAKER_THRESHOLD = 2  # a breaker_count of 0 never trips; 3 always does


# ─── synthetic-evidence grid (property 1) ───────────────────────────────────


def _patch_evidence(
    monkeypatch: pytest.MonkeyPatch,
    *,
    in_flight: int,
    exhausted: bool,
    ack_covers: bool,
    breaker_count: int,
    converged: bool,
) -> None:
    """Inject one independent evidence state into the five atoms the ladder reads.

    Patches the SOURCE module attributes (advance imports these names at call
    time from their defining modules), matching ``test_advance_refill``.
    """

    def fake_status(*, experiment_dir: Path, campaign_id: str) -> dict[str, Any]:
        return {
            "campaign_id": campaign_id,
            "iterations": 3,
            "in_flight": in_flight,
            "history": [],
            "run_ids": [],
        }

    def fake_budget(*, experiment_dir: Path, campaign_id: str, **_caps: Any) -> dict[str, Any]:
        return {
            "campaign_id": campaign_id,
            "spent": {"jobs": 3, "tasks": 3},
            "budget": {},
            "remaining": {"max_jobs": None},
            "projected": {},
            "coverage": {},
            "exhausted": exhausted,
            "reason": "max_jobs (cap met)" if exhausted else "within_budget",
        }

    def fake_converged(**_kw: Any) -> dict[str, Any]:
        return {"converged": converged, "reason": "max_iters_reached(3)" if converged else "n/a"}

    def fake_breaker(runs: Any) -> dict[str, Any]:
        return {"count": breaker_count, "run_ids": [], "last_status": None}

    def fake_resubmit(runs: Any) -> dict[str, Any]:
        # Held out of the grid — count 0 never trips regardless of the backstop
        # threshold, so the ladder's rule-4 slot is a pass-through here.
        return {"count": 0, "task_id": None, "per_task": {}}

    def fake_read_ack(experiment_dir: Path, campaign_id: str) -> dict[str, Any] | None:
        return {} if ack_covers else None

    def fake_ack_covers(ack: Any, spent: Any) -> bool:
        return ack_covers

    monkeypatch.setattr("hpc_agent.meta.campaign.atoms.status.campaign_status", fake_status)
    monkeypatch.setattr("hpc_agent.meta.campaign.atoms.budget.campaign_budget", fake_budget)
    monkeypatch.setattr(
        "hpc_agent.meta.campaign.atoms.converged.campaign_converged", fake_converged
    )
    monkeypatch.setattr(
        "hpc_agent.meta.campaign.atoms.circuit_breaker.consecutive_terminal_failures", fake_breaker
    )
    monkeypatch.setattr(
        "hpc_agent.meta.campaign.atoms.resubmit_cap.max_task_resubmits", fake_resubmit
    )
    monkeypatch.setattr("hpc_agent.meta.campaign.budget_ack.read_budget_ack", fake_read_ack)
    monkeypatch.setattr("hpc_agent.meta.campaign.budget_ack.ack_covers_spend", fake_ack_covers)


def _reference_sync_decision(
    *,
    in_flight: int,
    exhausted: bool,
    ack_covers: bool,
    breaker_count: int,
    converged: bool,
) -> str:
    """Independent restatement of the synchronous precedence ladder.

    Mirrors ``advance.py::campaign_advance`` sync ``rules`` order exactly:
    over_budget → wait_in_flight → circuit_breaker → resubmit_cap(off) →
    converged → continue.
    """
    if exhausted and not ack_covers:
        return "stop_over_budget"
    if in_flight > 0:
        return "wait_in_flight"
    if breaker_count >= _BREAKER_THRESHOLD:  # threshold pinned > 0
        return "stop_circuit_breaker"
    # resubmit_cap held at count 0 — never fires.
    if converged:
        return "stop_converged"
    return "continue"


_GRID = list(
    itertools.product(
        (0, 2),  # in_flight  (0..N)
        (False, True),  # budget exhausted
        (False, True),  # ack covers spend (fresh vs stale/absent)
        (0, 3),  # breaker count (< / >= threshold 2)
        (False, True),  # converged
    )
)


@pytest.mark.parametrize(
    ("in_flight", "exhausted", "ack_covers", "breaker_count", "converged"),
    _GRID,
    ids=[f"if{i}-exh{int(e)}-ack{int(a)}-brk{b}-cvg{int(c)}" for (i, e, a, b, c) in _GRID],
)
def test_flag_off_is_byte_identical_to_sync_reference(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    in_flight: int,
    exhausted: bool,
    ack_covers: bool,
    breaker_count: int,
    converged: bool,
) -> None:
    """Across the whole evidence grid, the flag-off decision equals the sync
    reference AND the async-only ``refill`` outcome is unreachable."""
    _patch_evidence(
        monkeypatch,
        in_flight=in_flight,
        exhausted=exhausted,
        ack_covers=ack_covers,
        breaker_count=breaker_count,
        converged=converged,
    )
    out = campaign_advance(
        experiment_dir=tmp_path,
        campaign_id=_CID,
        circuit_breaker_failures=_BREAKER_THRESHOLD,
        # async_refill defaults False (opt-in). max_in_flight is ignored off.
    )
    expected = _reference_sync_decision(
        in_flight=in_flight,
        exhausted=exhausted,
        ack_covers=ack_covers,
        breaker_count=breaker_count,
        converged=converged,
    )
    assert out["decision"] == expected
    # async-only branches are UNREACHABLE with the flag off.
    assert out["decision"] != "refill"
    assert out["refill_count"] is None


def test_async_branch_is_gated_not_dead(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The SAME steady-state evidence the sync ladder answers ``wait_in_flight``
    for is answered ``refill`` once the flag is on — proving ``_refill`` is real
    and reachable only behind the opt-in (byte-identity is a gate, not a
    dead branch)."""
    _patch_evidence(
        monkeypatch,
        in_flight=2,
        exhausted=False,
        ack_covers=False,
        breaker_count=0,
        converged=False,
    )
    off = campaign_advance(
        experiment_dir=tmp_path, campaign_id=_CID, circuit_breaker_failures=_BREAKER_THRESHOLD
    )
    assert off["decision"] == "wait_in_flight"
    assert off["refill_count"] is None

    on = campaign_advance(
        experiment_dir=tmp_path,
        campaign_id=_CID,
        circuit_breaker_failures=_BREAKER_THRESHOLD,
        async_refill=True,
        max_in_flight=4,
    )
    assert on["decision"] == "refill"
    assert on["refill_count"] == 2  # min(K-in_flight=2, unbounded)


# ─── real-journal anchors: reference == on-disk reality ──────────────────────


def _seed_iteration(experiment_dir: Path, *, run_id: str, campaign_id: str, status: str) -> None:
    """Seed a real sidecar + journal RunRecord (mirrors the circuit-breaker test)."""
    from hpc_agent.state.journal import upsert_run
    from hpc_agent.state.run_record import RunRecord
    from hpc_agent.state.runs import write_run_sidecar

    write_run_sidecar(
        experiment_dir,
        run_id=run_id,
        cmd_sha="0" * 12,
        hpc_agent_version="0.0.0+test",
        submitted_at="2026-01-01T00:00:00Z",
        executor="hpc_user_tasks",
        result_dir_template="results/{run_id}/{task_id}",
        task_count=1,
        tasks_py_sha="0" * 12,
        campaign_id=campaign_id,
        profile="ml",
        cluster="hoffman2",
        remote_path="/u/scratch/exp",
    )
    upsert_run(
        experiment_dir,
        RunRecord(
            run_id=run_id,
            profile="ml",
            cluster="hoffman2",
            ssh_target="user@host",
            remote_path="/scratch/exp",
            job_name="ml",
            job_ids=["1"],
            total_tasks=1,
            submitted_at="2026-01-01T00:00:00+00:00",
            experiment_dir=str(experiment_dir.resolve()),
            campaign_id=campaign_id,
            status=status,
        ),
    )


def test_anchor_flag_off_idle_continues(journal_home: Path, tmp_path: Path) -> None:
    """Real empty journal, flag off → continue (grid reference point in_flight=0,
    nothing tripped)."""
    _seed_iteration(tmp_path, run_id="r0", campaign_id="A", status="complete")
    out = campaign_advance(experiment_dir=tmp_path, campaign_id="A")
    assert out["decision"] == "continue"
    assert out["refill_count"] is None


def test_anchor_flag_off_in_flight_waits(journal_home: Path, tmp_path: Path) -> None:
    """Real in-flight run, flag off → wait_in_flight (reference in_flight>0)."""
    _seed_iteration(tmp_path, run_id="r0", campaign_id="A", status="in_flight")
    out = campaign_advance(experiment_dir=tmp_path, campaign_id="A")
    assert out["decision"] == "wait_in_flight"
    assert out["refill_count"] is None


def test_anchor_flag_off_breaker_stops(journal_home: Path, tmp_path: Path) -> None:
    """Real consecutive terminal failures, flag off → stop_circuit_breaker
    (reference breaker>=threshold)."""
    _seed_iteration(tmp_path, run_id="r0", campaign_id="A", status="failed")
    _seed_iteration(tmp_path, run_id="r1", campaign_id="A", status="failed")
    out = campaign_advance(
        experiment_dir=tmp_path, campaign_id="A", circuit_breaker_failures=_BREAKER_THRESHOLD
    )
    assert out["decision"] == "stop_circuit_breaker"
    assert out["refill_count"] is None


# ─── livelock guard: refill routed ONLY when advance decides refill ──────────


def test_livelock_guard_refill_only_when_advance_refills(
    journal_home: Path, tmp_path: Path
) -> None:
    """``load_context._async_should_refill`` routes a refill step only when
    ``campaign-advance`` authoritatively decides ``refill`` — a full pool (which
    advance answers ``wait_in_flight``) does NOT route refill, closing the
    standalone-``in_flight < K`` livelock (``load_context.py::_async_should_refill``).
    """
    from hpc_agent.meta.campaign.atoms.load_context import _async_should_refill
    from hpc_agent.meta.campaign.manifest import write_manifest

    # Free slot: one in flight, K=4 → advance decides refill → route refill.
    _seed_iteration(tmp_path, run_id="r0", campaign_id="A", status="in_flight")
    write_manifest(tmp_path, campaign_id="A", async_refill=True, max_in_flight=4)
    assert _async_should_refill(tmp_path, [{"campaign_id": "A"}]) is True

    # Full pool: same one in flight but K=1 → advance answers wait_in_flight →
    # NO refill step (the pool-full livelock guard).
    write_manifest(tmp_path, campaign_id="A", async_refill=True, max_in_flight=1)
    assert _async_should_refill(tmp_path, [{"campaign_id": "A"}]) is False


def test_livelock_guard_sync_campaign_never_refills(journal_home: Path, tmp_path: Path) -> None:
    """A campaign with no async opt-in never routes a refill step — the default
    is byte-identical (no manifest / async_refill unset)."""
    from hpc_agent.meta.campaign.atoms.load_context import _async_should_refill

    _seed_iteration(tmp_path, run_id="r0", campaign_id="A", status="in_flight")
    # No manifest written → async opt-in absent.
    assert _async_should_refill(tmp_path, [{"campaign_id": "A"}]) is False
