"""The harness-agnostic spawn-request contract.

A *delegated workflow spawn* has the same shape no matter which harness
intercepts it — the Claude Code ``spawn_guard`` PreToolUse hook today,
a MARs sub-agent interceptor tomorrow. This module is the single source
of truth for that shape: the workflow registry, the request model, and
the JSON envelope key. Each harness writes only a thin adapter that
extracts a request from its own spawn mechanism and feeds it to
:func:`hpc_agent.atoms.spawn_prompt.validate_and_render` — it never
re-declares the workflow set or re-implements validation.

Kept under ``_schema_models`` so wire-schema models (the ``load-context``
``delegate`` block) can reference :class:`SpawnRequest` without a
logic-layer import. The logic over this contract lives in
:mod:`hpc_agent.atoms.spawn_prompt`.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, field_validator

# The JSON key wrapping a spawn request when it travels as a Task prompt:
# ``{"hpc_spawn": {workflow, experiment_dir, fields}}``.
SPAWN_KEY = "hpc_spawn"

# The workflows that may be delegated. Kept consistent with
# WORKFLOW_SKILLS by test_spawn_prompt.test_workflow_name_matches_registry.
WorkflowName = Literal["submit", "status", "aggregate", "campaign"]

# workflow id → the skill the spawned subagent invokes via the Skill tool.
WORKFLOW_SKILLS: dict[str, str] = {
    "submit": "hpc-submit",
    "status": "hpc-status",
    "aggregate": "hpc-aggregate",
    "campaign": "hpc-campaign",
}


class SpawnRequest(BaseModel):
    """A delegated workflow spawn — the contract every harness shares.

    The agent supplies only ``workflow`` (constrained to the registry)
    and ``fields`` (invocation data); the prompt scaffold around them is
    generated by ``render_spawn_prompt``. ``extra="forbid"`` rejects any
    other key, so a drifting agent cannot smuggle instructions through a
    bogus field.
    """

    model_config = ConfigDict(extra="forbid")

    workflow: WorkflowName
    experiment_dir: str = "."
    fields: dict[str, Any] = {}

    @field_validator("experiment_dir")
    @classmethod
    def _single_line(cls, value: str) -> str:
        if "\n" in value or "\r" in value:
            raise ValueError("experiment_dir must be a single-line string")
        return value
