"""HPC chunking shim — translates chunk_id/total_chunks to <executor interface>.

Generated by claude-hpc /submit for <project name>.
Inspect / modify the translate() function if the data pipeline changes.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

_CACHE_FILE = "_shim_cache.json"


def translate(chunk_id: int, total_chunks: int) -> list[str]:
    """Return CLI args to append to the downstream executor command.

    This is the experiment-specific part. Adapt to your data pipeline.
    Examples:
      - Range split: determine total_rows, compute --start/--end
      - File split:  list files, select subset for this chunk
      - Date split:  compute date window from chunk index
    """
    # --- EDIT BELOW for your experiment ---
    total_items = _cached_total_items()
    base = total_items // total_chunks
    remainder = total_items % total_chunks
    start = base * chunk_id + min(chunk_id, remainder)
    end = start + base + (1 if chunk_id < remainder else 0)
    return ["--start", str(start), "--end", str(end)]


def _cached_total_items() -> int:
    """Compute and cache the total item count for splitting."""
    if _CACHE_FILE and os.path.isfile(_CACHE_FILE):
        with open(_CACHE_FILE) as f:
            cache = json.load(f)
        if "total_items" in cache:
            return cache["total_items"]

    total = _compute_total_items()

    if _CACHE_FILE:
        cache = {}
        if os.path.isfile(_CACHE_FILE):
            with open(_CACHE_FILE) as f:
                cache = json.load(f)
        cache["total_items"] = total
        tmp = _CACHE_FILE + ".tmp"
        with open(tmp, "w") as f:
            json.dump(cache, f)
        os.replace(tmp, _CACHE_FILE)
    return total


def _compute_total_items() -> int:
    """Determine the total number of items to split across chunks.

    --- EDIT THIS for your experiment ---
    Run the data pipeline up to the point where you know the array length,
    then return that length.
    """
    raise NotImplementedError("Fill in your data pipeline here")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Translate chunk_id/total_chunks for HPC dispatch",
    )
    parser.add_argument("--chunk-id", type=int, required=True)
    parser.add_argument("--total-chunks", type=int, required=True)
    args, downstream = parser.parse_known_args()

    if downstream and downstream[0] == "--":
        downstream = downstream[1:]
    if not downstream:
        parser.error("no downstream command provided after --")

    extra_args = translate(args.chunk_id, args.total_chunks)

    cmd = downstream + extra_args
    print(f"[shim] chunk {args.chunk_id}/{args.total_chunks} -> {' '.join(extra_args)}")
    sys.exit(subprocess.run(cmd).returncode)


if __name__ == "__main__":
    main()
