"""Generate docs/generated/harness-runbook.md — the prose-neutral harness runbook.

The workflow procedure is CODE-HOMED, not prose-homed. `_wire/spawn_contract.py::
DECISION_POINTS` enumerates every judgement/code branch of the four workflows,
each tagged `code` vs `judgement` and bound to a backing primitive; `infra/
block_chain.py` owns the block SEQUENCE (`ORDER`) and the consent boundaries
(`GATED_BLOCKS`). The agent-facing SKILL.md prose that WRAPS this procedure is
Claude-idiom-saturated (anti-vendor-lockout §1 prose-saturation inventory,
`docs/plans/anti-vendor-lockout-2026-07-17.md`). A FOREIGN harness needs the
procedure WITHOUT those idioms.

This script PROJECTS the code-homed procedure into a harness-neutral runbook so a
non-Claude harness drives the workflows against the `hpc-agent` CLI (the invariant
substrate, `docs/internals/harness-contract.md`) without reading a SKILL.md. The
vocabulary is the CLI verbs; there are NO tool-call / backgrounding / harness-UI
idioms. Edit `DECISION_POINTS` / `block_chain`, NEVER this generated prose (T5/R5).

ONE section is GENERATOR-HOMED prose rather than a projection: the
post-exploration CHECKER CONFORMANCE WALKTHROUGH (``_checker_section``). The
checker chain (the landed `adopt-run` series,
`docs/plans/expost-trust-2026-07-30.md`) is a plain verb chain, not a
block-drive workflow, so it has no `DECISION_POINTS` / `block_chain` home to
project from. The walkthrough states that chain and the harness conformance
rules in the same harness-neutral register; if the chain ever lands in the
code-homed tables, the walkthrough re-projects from there.

A `regen_all` step. Invoke exactly two ways::

    python scripts/build_harness_runbook.py --check   # gate: report drift
    python scripts/build_harness_runbook.py --write   # apply: regenerate

Bare invocation is refused (rc 2): this generator has no safe default mode.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Import the in-tree source without requiring an editable install (matches the
# other generators' subprocess-isolation model). A plugin's verbs never enter
# this core projection, so disable them for a stable, core-only render.
os.environ.setdefault("HPC_AGENT_DISABLE_PLUGINS", "1")
sys.path.insert(0, str(REPO_ROOT / "src"))

from hpc_agent._wire.spawn_contract import DECISION_POINTS, DecisionPoint  # noqa: E402
from hpc_agent.infra.block_chain import GATED_BLOCKS, ORDER  # noqa: E402

OUT = REPO_ROOT / "docs" / "generated" / "harness-runbook.md"

BANNER = (
    "<!-- AUTO-GENERATED. DO NOT EDIT BY HAND. "
    "Regenerated by `python scripts/build_harness_runbook.py`. -->"
)

# The Claude-idiom denylist (anti-vendor-lockout §1 prose-saturation inventory):
# no rendered line may carry one. Pinned by the runbook's test. This projection
# speaks CLI verbs only; the constant is exported so the test reads ONE source.
CLAUDE_IDIOM_DENYLIST: tuple[str, ...] = (
    "run_in_background",
    "AskUserQuestion",
    "CronCreate",
    "CronDelete",
    "tool call",
    "final action",
    "Skill(",
)

# Harness-neutral gloss for each DecisionPoint field. The raw tags are already
# vendor-neutral; the gloss states what each MEANS to a driving harness.
_KIND_GLOSS: dict[str, str] = {
    "gate": "gate (a pass/fail the block decides)",
    "selection": "selection (choose one of several branches)",
    "plan": "plan (compute a parameterisation)",
    "branch": "branch (switch on observed state)",
}
_DECIDED_BY_GLOSS: dict[str, str] = {
    "code": "code (a primitive's envelope records the outcome on disk — verifiable, reproducible)",
    "judgement": "judgement (a genuine break in control flow the driving agent chooses)",
}


def _preamble() -> str:
    """The harness-neutral driving protocol, stated ONCE for all workflows."""
    return "\n".join(
        (
            "# The harness runbook",
            "",
            "A **harness-neutral** projection of the code-homed workflow procedure. The",
            "procedure lives in code, not prose: `_wire/spawn_contract.py::DECISION_POINTS`",
            "enumerates every decision branch of the four workflows (each tagged `code` vs",
            "`judgement` and bound to a backing verb), and `infra/block_chain.py` owns the",
            "block SEQUENCE and the consent boundaries. This page states that procedure for a",
            "harness that is NOT Claude Code — the `hpc-agent` CLI verbs are the whole",
            "vocabulary (the CLI is the invariant substrate; see",
            "`docs/internals/harness-contract.md`). It carries NO harness-specific idioms; a",
            "Claude-Code SKILL.md is one *profile* of this runbook, not its source of truth.",
            "",
            "## How a harness drives any workflow",
            "",
            "1. **Run the driver.** Invoke `block-drive` with the workflow's first block. The",
            "   BLOCKS are the execution — code does the SSH, staging, canary, submit, watch,",
            "   and harvest — and `block-drive` owns the sequencing table; the harness never",
            "   hand-authors a block spec.",
            "2. **Relay each decision brief.** When a block returns a brief, present it to the",
            "   human VERBATIM. Deterministic code renders the brief; the harness does not",
            "   interpret raw results or resolve the decision itself.",
            "3. **Park at a consent boundary.** Before a block that mutates the cluster the",
            "   driver PARKS and waits for a human greenlight — it never self-advances past a",
            "   consent boundary (the blocks marked *consent boundary* below).",
            "4. **Commit a typed `y`.** A human types `y` (or a nudge). The harness commits it",
            "   through `append-decision`, which records the approved input spec to the",
            "   journal's `resolved` set. A bare `y` stands — no gate is tightened to buy",
            "   portability.",
            "5. **Advance.** The next `block-drive` tick consumes the approved spec and moves",
            "   to the successor block. Repeat until the chain reaches a terminal or a human",
            "   branch (no deterministic successor).",
            "",
            "The consent boundary protocol — **park → typed `y` → `append-decision` → the",
            "driver advances** — is identical for every workflow; only the block sequence and",
            "the decision points differ. A workflow with no consent boundary (see below) runs",
            "its chain without a per-step human gate.",
        )
    )


def _decision_table(points: tuple[DecisionPoint, ...]) -> list[str]:
    """The decision-point table for one workflow (id | shape | decided by | backing verb)."""
    rows = [
        "| Decision point | Shape | Decided by | Backing verb |",
        "|---|---|---|---|",
    ]
    for p in points:
        kind = _KIND_GLOSS.get(p.kind, p.kind)
        decided = _DECIDED_BY_GLOSS.get(p.decided_by, p.decided_by)
        verb = f"`{p.primitive}`" if p.primitive else "— (no backing verb)"
        rows.append(f"| `{p.id}` | {kind} | {decided} | {verb} |")
    return rows


def _workflow_section(workflow: str, points: tuple[DecisionPoint, ...]) -> str:
    """Render one workflow: block sequence, consent boundaries, decision table."""
    blocks = ORDER.get(workflow, [])
    gated_here = [b for b in blocks if b in GATED_BLOCKS]

    lines = [f"## `{workflow}`", ""]

    # Block sequence — the linear chain, consent boundaries flagged inline.
    if blocks:
        seq = " → ".join(
            f"`{b}`" + (" *(consent boundary)*" if b in GATED_BLOCKS else "") for b in blocks
        )
        lines += ["**Block sequence.**", "", seq, ""]
    else:
        lines += ["**Block sequence.** (no linear block chain — event-driven).", ""]

    # Consent boundaries — the park → typed y → append-decision protocol, concrete.
    if gated_here:
        boundary_list = ", ".join(f"`{b}`" for b in gated_here)
        lines += [
            "**Consent boundaries.** "
            f"The driver PARKS before {boundary_list} — each mutates the cluster and "
            "requires a journaled human greenlight. At each: relay the brief, a human types "
            "`y`, `append-decision` commits the approved spec, and the next `block-drive` "
            "tick advances into the block. The driver never enters one of these blocks "
            "without a committed `y` OR a live standing consent that covers it "
            "(`ops/overnight.py` owns the consumable sets; consumptions are ledgered).",
            "",
        ]
    else:
        lines += [
            "**Consent boundaries.** None — every block in this chain is ungated and the "
            "driver chains through in code (a greenlight, when this workflow needs one, is "
            "committed once at start, not per block).",
            "",
        ]

    # Decision points — the code-homed branch table.
    lines += ["**Decision points.**", ""]
    lines += _decision_table(points)
    lines += [""]
    return "\n".join(lines)


def _checker_section() -> str:
    """The post-exploration checker path — a GENERATOR-HOMED conformance walkthrough.

    Unlike the workflow sections above (projections of `DECISION_POINTS` /
    `block_chain`), the checker chain (the landed `adopt-run` series, the
    expost-trust plan `docs/plans/expost-trust-2026-07-30.md`) is a plain verb
    chain, not a block-drive workflow, so it has no code-homed tables to
    project from. This walkthrough states it — plus the harness conformance
    rules — in the same harness-neutral register, so a foreign harness can
    drive the checker against the CLI verbs.
    """
    lines = [
        "## The post-exploration checker path",
        "",
        "The workflows above mint evidence DURING execution, under observation. The",
        "checker path is the AFTER-THE-FACT instrument: a run that already completed —",
        "submitted by any means, observed by nothing — is adopted and checked ex post.",
        "The principle it implements: **gate by irreversibility and attestation, never",
        "by step** (`docs/plans/expost-trust-2026-07-30.md`). Exploration stays fast and",
        "ungated; verification is relocated to after the fact.",
        "",
        "The path is a plain verb chain, not a block-drive workflow: the harness invokes",
        "each verb directly and relays each envelope.",
        "",
        "**The chain.**",
        "",
        "`adopt-run` → `aggregate-check` → `aggregate-run` → `verify-reproduction`",
        "(external-baseline) → `evidence-brief`",
        "",
        "1. **Adopt the run.** `adopt-run` mints the run record from what ACTUALLY EXISTS —",
        "   the scheduler's observed state plus the human's adoption facts.",
        "2. **Gate, then reduce.** `aggregate-check` runs the readiness + integrity gate;",
        "   `aggregate-run` runs the deterministic combine + reduce. Every aggregate number",
        "   is computed by the REDUCER — never by the driving agent.",
        "3. **Claim-check.** `verify-reproduction` with an `external_baseline` block compares",
        "   the reduced numbers against human-authored claimed values under a caller",
        "   tolerance. The receipt kind is `claim-check` — NEVER `reproduction`.",
        "4. **Attest.** `evidence-brief` projects the run's durable records into the evidence",
        "   digest the human attests against; the decision journal records the outcome.",
        "",
        "**Consent.** No block-drive sequencing applies, but the consent posture is",
        "unchanged: `aggregate-run` carries its greenlight gate INSIDE the verb body — a call",
        "the run's journal does not greenlight is refused with a self-remediating message,",
        "and the greenlight is committed through `append-decision` exactly as in the protocol",
        "above.",
        "",
        "**Conformance rules for the driving harness.**",
        "",
        "1. **Adoption facts are ELICITED, never invented.** Take them from the human's",
        "   utterance or from observed scheduler state; a field that is unknown stays unknown.",
        "2. **`cmd_sha` is DERIVED from the exact command** the run actually executed — never",
        "   free-typed, never reconstructed from memory.",
        "3. **`claimed_values` are human-authored free text.** The harness transcribes them",
        "   verbatim into the `external_baseline` spec; it never rounds, normalises, or",
        "   corrects them.",
        "4. **Aggregate numbers come ONLY from the reducer.** The harness never computes,",
        "   averages, or interpolates a number the reducer did not emit.",
        "5. **Code renders are relayed VERBATIM.** The verdict sentence, the briefs, and the",
        "   receipts are deterministic projections; the harness presents them unchanged and",
        "   does not characterise match or mismatch in its own words.",
        '6. **A claim-check is NEVER reported as a reproduction.** "Reproduced" requires two',
        "   OBSERVED runs; an adopted run was never observed. The honest report is the",
        '   code-rendered verdict — for an adopted run, "the claim is consistent with the',
        "   adopted run's records (within caller tolerance)\" — or a finding that names the",
        "   moved dimension. Nothing more.",
        "",
    ]
    return "\n".join(lines)


def render_runbook(
    decision_points: dict[str, tuple[DecisionPoint, ...]] = DECISION_POINTS,
) -> str:
    """Project the code-homed procedure into the harness-neutral runbook markdown.

    Covers EVERY workflow in *decision_points* (the completeness contract: a
    workflow added to `DECISION_POINTS` without a regen fails `--check`). The
    workflow order follows the dict's insertion order — the canonical order the
    contract declares. The generator-homed checker conformance walkthrough
    (`_checker_section`) follows the projected workflows.
    """
    parts = [BANNER, "", _preamble(), ""]
    for workflow, points in decision_points.items():
        parts.append(_workflow_section(workflow, points))
    parts.append(_checker_section())
    return "\n".join(parts).rstrip("\n") + "\n"


def build(*, out_path: Path = OUT, write: bool) -> int:
    """Regenerate (or --check) the runbook; return 0 iff in sync."""
    rendered = render_runbook()
    current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
    if rendered == current:
        print(f"harness runbook up to date ({len(DECISION_POINTS)} workflows)")
        return 0
    if not write:
        print(
            "ERROR: harness runbook out of date — run "
            "'python scripts/build_harness_runbook.py --write' to regenerate",
            file=sys.stderr,
        )
        return 1
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"regenerated harness runbook ({len(DECISION_POINTS)} workflows)")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    check = "--check" in args
    write = "--write" in args
    if check == write:  # neither, or both — refuse
        print(
            "usage: python scripts/build_harness_runbook.py --check | --write\n"
            "  --check  gate: rebuild-and-compare the runbook, report drift\n"
            "  --write  apply: regenerate the runbook in place",
            file=sys.stderr,
        )
        return 2
    return build(write=write)


if __name__ == "__main__":
    sys.exit(main())
