"""Generate docs/generated/operations.md from `hpc-agent capabilities`.

Read-time view of the same operation catalog that an external agent
gets at runtime via the `capabilities` subcommand. Both surfaces consume
exactly the same data — the script subprocess-calls the CLI and parses
the JSON envelope, so this doc is provably in sync with what runtime
introspection returns.

Usage:
    uv run python scripts/build_operations_index.py [--check]

--check exits non-zero if docs/generated/operations.md is out of date (CI gate).
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

# Import via direct path append so this script runs without an editable
# install ("python scripts/build_operations_index.py").
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _shared import REPO_ROOT, sort_verbs, summarize_side_effects  # noqa: E402

OUT = REPO_ROOT / "docs" / "generated" / "operations.md"

VERB_DESCRIPTIONS = {
    "query": "Read-only, no side effects. Freely composable; cacheable.",
    "validate": "Read + binary health check. Same composability as `query`.",
    "mutate": ("Writes to journal / sidecar. Need flock + idempotency-key consideration."),
    "submit": "Records a new submission (sidecar write + journal entry).",
    "scaffold": "Creates new files (e.g. starter executor templates).",
    "workflow": (
        "End-to-end pipelines composing other primitives. Same envelope shape as primitives — "
        "indistinguishable to higher-level callers (the Composite property)."
    ),
}


def fetch_operations() -> list[dict]:
    """Subprocess-call `hpc-agent capabilities` and parse the operations array."""
    result = subprocess.run(
        ["hpc-agent", "capabilities"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    lines = result.stdout.strip().splitlines()
    if not lines:
        raise SystemExit("hpc-agent capabilities produced no stdout")
    envelope = json.loads(lines[-1])
    if not envelope.get("ok"):
        raise SystemExit(f"capabilities envelope returned ok=false: {envelope}")
    data = envelope.get("data") or {}
    if not isinstance(data, dict):
        raise SystemExit(f"capabilities envelope returned non-dict data: {type(data).__name__}")
    return data.get("operations", [])


def render_row(op: dict) -> str:
    name = op["name"]
    cli = op.get("cli") or "_(Python-only)_"
    py = op.get("python") or "_(none)_"
    inp = f"`hpc_agent/schemas/{op['input_schema']}`" if op.get("input_schema") else "—"
    out = f"`hpc_agent/schemas/{op['output_schema']}`" if op.get("output_schema") else "—"
    idem = "✓" if op.get("idempotent") else "✗"
    # Use the shared renderer so structured {verb: target} side-effect
    # entries from primitive frontmatter survive — the previous inline
    # ", ".join(side_effects) silently dropped them.
    sfx = summarize_side_effects(op.get("side_effects") or [])
    return (
        f"| [`{name}`](../primitives/{name}.md) | {idem} | {sfx} | "
        f"`{cli}` | `{py}` | {inp} | {out} |"
    )


def render_section(verb: str, ops: list[dict]) -> str:
    head = (
        f"## `{verb}` ({len(ops)})\n\n"
        f"{VERB_DESCRIPTIONS.get(verb, '')}\n\n"
        "| Operation | Idempotent | Side effects | CLI | Python | Input schema | Output schema |\n"
        "|---|---|---|---|---|---|---|\n"
    )
    rows = "\n".join(render_row(op) for op in sorted(ops, key=lambda o: o["name"]))
    return head + rows + "\n"


def build_index(operations: list[dict]) -> str:
    by_verb: dict[str, list[dict]] = {}
    for op in operations:
        by_verb.setdefault(op["verb"], []).append(op)

    sorted_verbs = sort_verbs(list(by_verb.keys()))
    sections = "\n".join(render_section(v, by_verb[v]) for v in sorted_verbs)
    workflow_count = len(by_verb.get("workflow", []))
    primitive_count = len(operations) - workflow_count

    intro = (
        "<!-- AUTO-GENERATED. DO NOT EDIT BY HAND. "
        "Regenerated by `python scripts/build_operations_index.py`. -->\n\n"
        "# Operations\n\n"
        "Auto-generated from `hpc-agent capabilities`. Run "
        "`uv run python scripts/build_operations_index.py` after editing any primitive "
        "frontmatter; the script subprocess-calls the CLI and parses the same JSON envelope "
        "an external agent would get at runtime, so this page is provably in sync with "
        "runtime introspection.\n\n"
        f"**{len(operations)} operations total**: {primitive_count} primitive atoms + "
        f"{workflow_count} workflow atoms.\n\n"
        "## How to read this page\n\n"
        "Every operation in `hpc-agent` is a CLI atom or a Python-only primitive that emits "
        "the same `{ok, data, error_code}` envelope shape "
        "(see `docs/reference/cli-spec.md`). Workflow "
        "atoms compose primitive atoms but are externally indistinguishable from primitives — "
        "that's the Composite property that makes higher-level workflows like campaigns work.\n\n"
        "**Composability rule**: any operation can invoke any other operation by shelling to "
        "its CLI form (or importing its Python form). Higher-level workflows (e.g. "
        "`submit-flow → monitor-flow → aggregate-flow` chained by a campaign loop) are just "
        "operations that invoke other operations.\n\n"
        "**Discoverability**: `hpc-agent capabilities` returns this same catalog at "
        "runtime in `data.operations`. Agents that don't have access to this page can "
        "introspect the framework via that subprocess call.\n\n"
    )
    return intro + sections + "\n"


def main() -> int:
    check = "--check" in sys.argv
    operations = fetch_operations()
    new = build_index(operations)
    if OUT.exists() and OUT.read_text(encoding="utf-8") == new:
        print(f"operations index up to date ({len(operations)} operations)")
        return 0
    if check:
        print(
            "ERROR: docs/generated/operations.md out of date — run "
            "scripts/build_operations_index.py to regenerate",
            file=sys.stderr,
        )
        return 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(new, encoding="utf-8")
    print(f"regenerated docs/generated/operations.md ({len(operations)} operations)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
