"""The single source of truth for the delegated-workflow spawn contract.

A *delegated workflow spawn* has the same shape wherever it is consumed
inside hpc-agent — the ``hpc-agent run`` entrypoint, the
``load-context`` ``delegate`` block, the headless campaign driver. This
module owns that shape end to end:

* the **request** side — :class:`SpawnRequest`, the workflow registry,
  the JSON envelope key;
* the **decision points** — :data:`DECISION_POINTS`, the enumerated
  judgement branches each workflow reaches;
* the **report** side — :class:`WorkerReport`, the structured object a
  delegated worker returns.

so validation never forks across consumers. Each consumer is a thin
adapter feeding requests to
:func:`hpc_agent._kernel.extension.spawn_prompt.validate_and_render_parts` and
parsing reports with
:func:`hpc_agent._kernel.extension.spawn_prompt.parse_worker_report`; it never
re-declares the workflow set or re-implements validation.

Kept under ``_wire`` so wire-schema models (the ``load-context``
``delegate`` block) can reference :class:`SpawnRequest` without a
logic-layer import. The logic over this contract lives in
:mod:`hpc_agent._kernel.extension.spawn_prompt`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, field_validator

# The JSON key under which a spawn request travels in a JSON envelope:
# ``{"hpc_spawn": {workflow, experiment_dir, fields}}``.
SPAWN_KEY = "hpc_spawn"

# The workflows that may be delegated. Kept consistent with
# WORKFLOW_PROCEDURES by test_spawn_prompt.test_workflow_name_matches_registry.
WorkflowName = Literal["submit", "status", "aggregate", "campaign"]

# workflow id → the worker-prompt template inlined into the spawned
# subagent's cacheable prefix. Resolved by
# ``hpc_agent._kernel.extension.spawn_prompt._procedure_body`` (host: package data
# at ``hpc_agent/_kernel/extension/worker_prompts/<name>.md``; plugins
# overlay via the ``worker_prompt_assets`` attribute on their entry
# point). These are
# *not* Claude Code skills — a headless ``claude -p --bare`` worker has
# no Skill tool, so the procedure travels inside the prompt itself. See
# ``docs/internals/skill-policy.md`` for the forcing rule.
WORKFLOW_PROCEDURES: dict[str, str] = {
    "submit": "submit",
    "status": "status",
    "aggregate": "aggregate",
    "campaign": "campaign",
}


class SpawnRequest(BaseModel):
    """A delegated workflow spawn — the contract every consumer shares.

    The agent supplies only ``workflow`` (constrained to the registry)
    and ``fields`` (invocation data); the prompt scaffold around them is
    generated by ``render_spawn_prompt``. ``extra="forbid"`` rejects any
    other key, so a drifting agent cannot smuggle instructions through a
    bogus field.
    """

    model_config = ConfigDict(extra="forbid")

    workflow: WorkflowName
    experiment_dir: str = "."
    fields: dict[str, Any] = {}

    @field_validator("experiment_dir")
    @classmethod
    def _single_line(cls, value: str) -> str:
        if "\n" in value or "\r" in value:
            raise ValueError("experiment_dir must be a single-line string")
        return value


# ── decision points ─────────────────────────────────────────────────────────

# What shape a decision is.
DecisionKind = Literal["gate", "selection", "plan", "branch"]

# Who makes it: a deterministic primitive, or genuine LLM judgement.
DecidedBy = Literal["code", "judgement"]


@dataclass(frozen=True)
class DecisionPoint:
    """One enumerated decision a workflow reaches.

    A ``code`` point is produced by a deterministic primitive whose
    envelope already records the outcome on disk — so a worker's
    reported outcome is *verifiable*, not merely trusted, and the same
    on-disk state reproduces it. A ``judgement`` point is a genuine LLM
    choice; its rationale is the thing worth capturing.
    """

    id: str
    kind: DecisionKind
    decided_by: DecidedBy
    primitive: str | None  # backing operation (catalog name), if any


# The judgement branches of each workflow, derived from the skills' call
# sequences. A worker reports its decisions against these ids; an id not
# listed here is rejected by parse_worker_report. test_decision_points
# cross-checks every `primitive` against the operations catalog.
DECISION_POINTS: dict[str, tuple[DecisionPoint, ...]] = {
    "submit": (
        DecisionPoint("entry_path", "selection", "code", "suggest-setup-action"),
        DecisionPoint("prior_run", "branch", "code", "find-prior-run"),
        DecisionPoint("axis_class", "selection", "judgement", "classify-axis"),
        DecisionPoint("throughput_plan", "plan", "code", "plan-throughput"),
        DecisionPoint("canary", "gate", "code", "verify-canary"),
        DecisionPoint("preflight", "gate", "code", "check-preflight"),
        DecisionPoint("validate_campaign", "gate", "code", "validate-campaign"),
    ),
    "status": (
        DecisionPoint("surface", "selection", "judgement", None),
        DecisionPoint("lifecycle_dispatch", "branch", "code", "poll-run-status"),
        DecisionPoint("resubmit", "branch", "judgement", "resubmit-failed"),
        DecisionPoint("monitor_cadence", "plan", "code", "decide-monitor-arm"),
    ),
    "aggregate": (
        DecisionPoint("mode", "selection", "code", "aggregate-flow"),
        # 'partial_handling' switches on observable evidence via
        # decide-partial-handling: retry resolves decided_by=code while
        # combiner retries remain; once exhausted, the accept-partial-vs-retry
        # acceptability call escalates (the residue). Stays tagged judgement —
        # that escalating residue is the worst case it can reach.
        DecisionPoint("partial_handling", "branch", "judgement", "decide-partial-handling"),
        DecisionPoint("completeness", "gate", "code", "verify-aggregation-complete"),
        # 'reduce_locality' is decided deterministically by aggregate-flow's
        # mode=auto routing (cluster-reduce iff aggregate_cmd is set, else
        # combiner-only) — reduce where the data sits. It is not an LLM
        # judgement; the override is a caller spec field, not a branch the
        # worker reasons. Demoted judgement→code (the prior tag was inert).
        DecisionPoint("reduce_locality", "branch", "code", "aggregate-flow"),
    ),
    "campaign": (
        # 'path' (manual grid vs strategy-driven) is a structural fact about
        # tasks.py — classify-campaign-path resolves the common cases by AST
        # scan (decided_by=code) and escalates only the unparseable/unknown
        # tail, mirroring axis_class→classify-axis. Stays tagged judgement
        # because that escalating tail is the worst case it can reach.
        DecisionPoint("path", "selection", "judgement", "classify-campaign-path"),
        DecisionPoint("stochastic_marker", "gate", "code", "validate-stochastic-marker"),
        DecisionPoint("decide", "plan", "judgement", "campaign-advance"),
        DecisionPoint("convergence", "gate", "code", "campaign-converged"),
        DecisionPoint("budget", "gate", "code", "campaign-budget"),
        # 'concurrency' switches on observable evidence via decide-concurrency:
        # sequential resolves decided_by=code (no async support or no budget
        # headroom); only how-aggressive-within-the-safe-bound escalates (the
        # risk-appetite residue). Stays tagged judgement for that residue.
        DecisionPoint("concurrency", "selection", "judgement", "decide-concurrency"),
    ),
}


# ── report side ──────────────────────────────────────────────────────────────


def judgement_point_ids(workflow: str) -> frozenset[str]:
    """The ids of *workflow*'s ``decided_by="judgement"`` decision points.

    These are the genuine breaks in control flow — the branches a worker
    *chose* rather than the deterministic ``code``/``plan`` points whose
    outcome a backing primitive's envelope already records on disk. The
    judgement set is what :func:`parse_worker_report` requires a non-empty
    ``why`` for: a control-flow branch taken with no recorded rationale is
    the bug worth catching, not a state worth silently accepting.
    """
    return frozenset(
        point.id for point in DECISION_POINTS.get(workflow, ()) if point.decided_by == "judgement"
    )


class WorkerDecision(BaseModel):
    """One decision a delegated worker reports making.

    ``point`` must be a :class:`DecisionPoint` id for the worker's
    workflow — cross-checked by ``parse_worker_report``.

    At a ``decided_by="judgement"`` point — a genuine break in the control
    flow, not a parameter the deterministic layer computed — the rationale
    is the thing worth capturing (see :class:`DecisionPoint`): ``why`` is
    **required** (``parse_worker_report`` rejects an empty one at a
    judgement point), ``chosen`` names the branch taken, and ``rejected``
    lists the alternatives weighed and discarded — so the record is the
    *choice*, not merely an outcome tag. At a deterministic point these
    stay optional; the backing primitive's envelope is the authoritative
    record there.
    """

    model_config = ConfigDict(extra="ignore")

    point: str
    outcome: str
    why: str = ""
    chosen: str | None = None
    rejected: list[str] = []


class WorkerReport(BaseModel):
    """The structured object a delegated worker returns as its final message.

    ``extra="ignore"`` — lenient on a worker's *output* (an LLM may add a
    stray key), unlike the strict ``extra="forbid"`` on the
    :class:`SpawnRequest` *input* contract.
    """

    model_config = ConfigDict(extra="ignore")

    result: dict[str, Any] = {}
    decisions: list[WorkerDecision] = []
    anomalies: str = ""
