"""Minimal HPC executor scaffold — pure compute, no CLI surface.

This template lands in the experiment repo (e.g. ``src/<name>.py``)
and demonstrates the only contract every executor must satisfy:

    Expose ``compute(args) -> None``.

That's it. CLI dispatch lives in ``.hpc/cli.py`` (auto-generated by
``/submit-hpc`` in the experiment repo); the per-executor flag list
is declared in ``.hpc/tasks.py`` FLAGS, keyed by importable module
path. The dispatcher parses argv against the right FLAGS, then calls
``compute(args)`` here.

Cluster invocation:

    python -m cli src.<this_module> --output-file ... <other flags>

There is no ``if __name__ == "__main__":`` block here. The dispatcher
is the entry point — running this file directly with ``python`` won't
do anything useful.

Convention details:

* ``args.output_file`` is the only flag the framework guarantees
  (provided by ``generic_args()`` in every FLAGS list). All other
  flags come from the experiment's per-executor entry in
  ``.hpc/tasks.py`` FLAGS — e.g. ``flag("horizon", int, default=1)``
  becomes ``args.horizon``.
* Writes the per-task result to ``args.output_file`` (CSV / Parquet /
  JSON — format is the executor's call).
* Optionally calls
  :func:`claude_hpc.mapreduce.metrics_io.write_metrics` with a dict of
  scalar summaries when ``$RESULT_DIR`` is set, so the on-cluster
  combiner can aggregate per grid point. No-op outside the HPC
  dispatcher.

Smoke test during development::

    python -c "import argparse; \
               from src.<this_module> import compute; \
               compute(argparse.Namespace(output_file='/tmp/out.csv'))"
"""

# ruff: noqa: E501  (LLM-facing scaffolds read better with long lines)

from __future__ import annotations

import csv
import os
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import argparse


def compute(args: argparse.Namespace) -> None:
    """Run the experiment for one task and write its result file.

    TODO: replace with the experiment's real computation. The ``args``
    Namespace is whatever the dispatcher parsed from argv against this
    executor's per-key entry in ``.hpc/tasks.py`` FLAGS.
    """
    # Example minimal output: one-row CSV with a placeholder metric.
    result: dict[str, Any] = {"value": 0.0, "n_samples": 0}

    os.makedirs(os.path.dirname(args.output_file) or ".", exist_ok=True)
    with open(args.output_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(list(result.keys()))
        writer.writerow(list(result.values()))

    # Optional: emit metrics.json sidecar for the cluster combiner.
    # No-op outside the HPC dispatcher (when $RESULT_DIR is unset) so
    # the scaffold stays standalone-runnable for local smoke tests.
    if os.environ.get("RESULT_DIR"):
        from claude_hpc.mapreduce.metrics_io import write_metrics

        write_metrics(result)


# ── Common patterns (reference, not active code) ─────────────────────────
#
# The snippets below illustrate three typical compute() shapes. Copy and
# adapt the one that matches your experiment. None of them are baked
# into the framework — flags are declared in .hpc/tasks.py FLAGS.
#
# 1. ML training / forecasting (FLAGS: horizon, train_window, alpha, ...)
#
#    def compute(args):
#        df = load_data(args.data_path)
#        train, test = walk_forward_split(df, args.start, args.end, args.horizon)
#        model = fit(train, alpha=args.alpha)
#        preds = model.predict(test)
#        metrics = {"qlike": qlike(test.y, preds), "n_samples": len(test)}
#        write_csv(args.output_file, preds)
#        if os.environ.get("RESULT_DIR"):
#            from claude_hpc.mapreduce.metrics_io import write_metrics
#            write_metrics(metrics)
#
# 2. Simulation / seed-sweep (FLAGS: seed, steps, config, ...)
#
#    def compute(args):
#        rng = numpy.random.default_rng(args.seed)
#        traj = run_simulation(config=args.config, steps=args.steps, rng=rng)
#        scalars = summarize(traj)
#        write_json(args.output_file, scalars)
#
# 3. Sharded data-processing (FLAGS: shard_id, n_shards, input_glob, ...)
#
#    def compute(args):
#        files = sorted(glob.glob(args.input_glob))
#        my_files = files[args.shard_id::args.n_shards]
#        rows = sum((process(f) for f in my_files), [])
#        write_parquet(args.output_file, rows)
